### ISSUE TITLE
Editor - cursor not shown at correct place and graphic glitches

### ISSUE THREAD

**Issue by rpnfan** [UltimateHackingKeyboard/agent#2087]
In Agent 3.02 I have the problem that the cursor is not shown at the correct location. This makes editing very cumbersome. Deleting the Roaming folder and re-installing Agent 3.02 does not fix the problem.

![image](https://github.com/UltimateHackingKeyboard/agent/assets/51239533/5573aac6-579e-4e6b-9c28-d5c3c22154e6)

Also the highlight mode is mixed up:
![image](https://github.com/UltimateHackingKeyboard/agent/assets/51239533/ee948df7-43a9-40f9-bf4a-5dc740a7ac8f)

**Comment by mondalaci** [comment]
Can you reproduce this with Agent 3.0.1? I guess that the JetBrains Mono font added in 3.0.2 introduced this issue.

For the record, I can't reproduce this issue.

**Comment by rpnfan** [comment]
3.01 works fine. I just tested that a workaround with 3.02 is to decrease the display scaling from 175 to 150 % for my display (3840 x 2160 resolution). OS is Win 11.

**Comment by mondalaci** [comment]
Did your workaround work?

**Comment by rpnfan** [comment]
Sure, otherwise it would not be a workaround... ;-) So it is indeed a font / resolution problem.

**Comment by mondalaci** [comment]
Gotcha, thanks :)

@ert78gb Can you reproduce this?

**Comment by ert78gb** [comment]
I use macbook and I can't reproduce the issue.
I also have an old not 4k win 10 notebook. This notebook allow to set max 150% and I can't reproduce it neither of 100%, 125% or 150%.
I know these are not the same config. I just shared the info for the record.

We use monaco-editor under the hood.

I am upgrading the Jetbrains Mono font I hope it will help. If not we will continue the investigation.

**Comment by mondalaci** [comment]
Closing the issue, assuming it has been resolved. Feel free to reopen it if it persists in the next Agent release.

**Comment by rpnfan** [comment]
The problem persists in Agent 3.10.

**Comment by mondalaci** [comment]
Thanks for the heads-up!

@ert78gb Can you reproduce it?

**Comment by ert78gb** [comment]
I can't :(
I will upgrade electron and monaco-editor on the weekend. We will see is it solve the issue or not.

**Comment by mondalaci** [comment]
@rpnfan Can you still reproduce this issue with Agent 3.2.0?

**Comment by rpnfan** [comment]
Yes, nothing changes for me. Still the same problem. :-(

**Comment by mondalaci** [comment]
Do you have any other applications similarly affected? I'm asking because nobody else has reported this issue.

**Comment by ert78gb** [comment]
@rpnfan does the [web version](https://ultimatehackingkeyboard.github.io/agent/#/keymap/QWR) behave in the same way?

**Comment by rpnfan** [comment]
> Do you have any other applications similarly affected? I'm asking because nobody else has reported this issue.

Most programs work fine, but I had problems with a few indeed. That not many are reporting that is I think that not too many are using a 4K screen _and_ have the scaling set to 175%.

> @rpnfan does the [web version](https://ultimatehackingkeyboard.github.io/agent/#/keymap/QWR) behave in the same way?

No, that looks fine.

![image](https://github.com/UltimateHackingKeyboard/agent/assets/51239533/0e8cd061-8f3e-4cf3-9dd1-7b6d75057b37)

**Comment by mondalaci** [comment]
Which other applications are affected? Maybe they're also using Electron.

**Comment by rpnfan** [comment]
I do not think they are using Electron. I mostly had problems with (super) old software, like Labview which seems to use super outdated GUI builders. I do not know what they use, but almost sure not Electron.

**Comment by mondalaci** [comment]
@ert78gb Any ideas?

**Comment by ert78gb** [comment]
Yesterday, we released a new Agent version with upgraded electron. Does it solved the issue?

I dont know what is the solution, but I will find

**Comment by rpnfan** [comment]
I just wanted to test the new 3.2.1 version, but get an error when I check from Agent. And when I want to download it from Github I am missing the Win64 version (3.2. did still have that).

![image](https://github.com/UltimateHackingKeyboard/agent/assets/51239533/7c8b4b61-6061-4dd8-84c7-637ff0791eab)

**Comment by ert78gb** [comment]
3.2.1 has win64 version https://github.com/UltimateHackingKeyboard/agent/releases/download/v3.2.1/UHK.Agent-3.2.1-win-x64.exe

**Comment by pcooke9** [comment]
I have this issue as well. It persists with Agent v3.2.1.

I'm using a Samsung Q80T TV @ 4k resolution with Windows 11 Display Scaling set to 150%. It properly realigns if I change the scaling either higher or lower while Agent is open, but reverts after restarting Agent. It doesn't seem to matter what Windows scaling I use prior to launching Agent (including 100%). As long as I change it to something different after opening Agent, it will temporarily display correctly.

**Comment by rpnfan** [comment]
> 3.2.1 has win64 version https://github.com/UltimateHackingKeyboard/agent/releases/download/v3.2.1/UHK.Agent-3.2.1-win-x64.exe

Thanks, now I got a message in Agent 3.2 that I can upgrade and that worked fine. I now can also see the 64 Bit version on Github. But it was missing (with a few others) for sure.

> I have this issue as well. It persists with Agent v3.2.1.
> 
> I'm using a Samsung Q80T TV @ 4k resolution with Windows 11 Display Scaling set to 150%. It properly realigns if I change the scaling either higher or lower while Agent is open, but reverts after restarting Agent. It doesn't seem to matter what Windows scaling I use prior to launching Agent (including 100%). As long as I change it to something different after opening Agent, it will temporarily display correctly.

I just wanted to update my findings. Changing to 150 dpi is not a workaround any longer for me. Also no other resolution fixes the problem. I just tested your workaround and it is the same for me too. So changing to any other than the resolution at which Agent was started with, fixes the problem. But only, when the change is made will Agent is open. Changing back to the original resolution will introduce the error again. 

I also tried to test the different options for high dpi screens, none of them helped:

![image](https://github.com/UltimateHackingKeyboard/agent/assets/51239533/380dde39-5d54-48f1-9291-f7c00d8e0b6e)

**Comment by ert78gb** [comment]
@rpnfan Thank you for your time and patience. Finally, I could reproduce the issue on my windows machine. I created a fix that worked fine on my machine. I created a temporary release on my machine. You can download it from my [google drive](https://drive.google.com/file/d/1f0EBCIQExJ8jsAO__anozWi0Ujq6lB8S/view?usp=sharing).

Maybe the installer is not properly signed, because my windows machine reported some file access concurrency issue.
The release contains the #2130 and #2131.

If the fix works in your environment then we will create an official release too.

**Comment by rpnfan** [comment]
I just tested your new version and indeed it works flawlessly! :-)  I checked scaling from 100 % op to 250 %. No graphic glitches any longer 👍 

Thanks a lot.

**Comment by pcooke9** [comment]
Thanks, fixed for me as well.
