### ISSUE TITLE
blhost segfaults on Linux

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#681]
The firmware update process of Agent calls a command line utility called blhost. This utility is critical for the firmware update to be successful. Apparently, on some machines blhost segfaults for some reason, making the firmware update unsuccesful.

You can easily tell if blhost is the culprit. Consider the following firmware update log:

```
[00:51:25.742] [blhost] RUN: /tmp/.mount_UHK.Agp1hZSj/app/resources/packages/blhost/linux/x86_64/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[00:51:25.750] [blhost] EXIT_CODE: null
[00:51:25.750] [blhost] FINISHED: null
```

blhost should never return with null. If it does, it has most likely segfaulted. There is an easy and a hard way to solve this.

The easy way is to try to build blhost on your operating system, instead of using the binary provided by Agent. This may or may not work, but it's worth a try. You can clone the [UHK booltloader repo](https://github.com/UltimateHackingKeyboard/bootloader), then run `make` in its `validation/blhost/gcc` directory. Then according to your firmware update log, overwrite the blhost binary provided by Agent with your compiled version. In the above example blhost is located at `/tmp/.mount_UHK.Agp1hZSj/app/resources/packages/blhost/linux/x86_64/blhost`. Then retry the firmware update. You're welcome to let me know if it works.

The hard way is to reimplement blhost in TypeScript and make it a part of Agent. To be more exact, I'll reimplement [pyKBoot](https://github.com/molejar/pyKBoot) it also implements the KBOOT protocol, and  being written in Python, it's so much more readable than blhost. I'm confident that this will work, but it'll take me some time.

**Comment by iprok** [comment]
I have compiled and successfully started blhost, thank you! I'm attaching the binary here, may be it will help somebody.

@mondalaci can you please make a setting in agent to use external blhost? So that I can use my version easily.

**Comment by iprok** [comment]
> Please attach your compiled blhost binary. Seems like you forgot it.

https://github.com/UltimateHackingKeyboard/agent/files/2113028/blhost.gz

**Comment by mondalaci** [comment]
@iprok Thanks! Your blhost binary is larger than the previous one by about 50K, so it clearly differs. More importantly, it works on both of our machines, so it's probably a better choice, so I've just replaced the old one with it.

This gives me hope that this issue can be solved by recompiling blhost on the affected OSes. I believe the magic lies in finding a good combination of libusb and gcc versions. Newer versions should be generally better, unless a bug was introduced. Just for the record, would you include these version numbers here?

**Comment by iprok** [comment]
gentoo linux
libusb-1.0.21
glibc-2.26
and I use eudev-3.2.5 instead of general udev

**Comment by iprok** [comment]
gcc-6.4.0

**Comment by mondalaci** [comment]
@IzK666 Please try to update your firmware on Linux using the newly released [Agent 1.2.3](https://github.com/UltimateHackingKeyboard/agent/releases/tag/v1.2.3). It contains the new blhost binary built by @iprok which should not segfault anymore on Linux.

@spuder Would you please build a new blhost binary and replace the old one according to the above instructions? I'm pretty sure that the Mac version of blhost segfaults on your system when it accesses USB. A custom blhost build could solve this issue in a snap.

Please let me know how it works for you guys.

**Comment by iprok** [comment]
@mondalaci I also have mac with latest os x version and was able to update firmware successfully at the first try using "old" version of blhost before you've gave me building instructions.

And @spuder can start blhost. When I had segfaults I had them all times when tried to start blhost.

So I think it's separate problem on OS X. I have Macbook Air and @spuder has Pro. May some difference in hardware is root of the problem.

**Comment by mondalaci** [comment]
@iprok According to my memory, on some computers blhost works when not accessing USB and segfaults when accessing USB, so I still believe that rebuilding blhost on OSX is worth trying. The null return value of blhost within Agent also strongly suggests that it segfaults. The Macbook Pro may feature different hardware or OSX, gcc, libusb versions, and any of them can contribute to this problem.

**Comment by IzK666** [comment]
It doesn't update, but the errors are different. No more null exit codes.
<a href="https://pastebin.com/AuYaLKfq">My log</a>.

**Comment by mondalaci** [comment]
@IzK666 This looks better. According to the `/usr/lib/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found` error message, a dependent library is not found on your system.

@iprok: This should be solveable by statically linking libstdc++.so.6 into blhost. I'm not particularly well-versed at instructing the linker. Are you?

**Comment by luteijn** [comment]
Perhaps the options mentioned on https://stackoverflow.com/questions/6578484/telling-gcc-directly-to-link-a-library-statically might help here?

**Comment by IzK666** [comment]
@mondalaci I've installed the latest firmware (8.2.5).
I've used a live version of debian 9.4 and it throw no errors.
The other distro is optimized to be small and fast, but that could be the reason to have some libraries missing or use older versions.

**Comment by iprok** [comment]
I've compiled two versions of blhost:
Fully static: 
[blhost-static.gz](https://github.com/UltimateHackingKeyboard/agent/files/2120944/blhost-static.gz)
And partially static: 
[blhost-partialystatic.gz](https://github.com/UltimateHackingKeyboard/agent/files/2120945/blhost-partialystatic.gz)

Both are near 2,5MB size when unpacked.

**Comment by mondalaci** [comment]
@iprok Thanks so much! The fully static version should be the way to go. Let's not rely on possibly missing libraries. What is exactly the difference between the fully static and the partially static versions? Would you also paste the commands to build blhost both ways just in case?

@luteijn Thanks for the link!

@IzK666 Would you please give a try to the fully static blhost version that @iprok attached on the small distro on which @iprok's previous blhost version failed due to the missing dependency? I'd like to see if it works. If so, we'll use it in Agent going forward.

**Comment by luteijn** [comment]
I'm  not an expert on  appimage format, but I think it should be possible to include all the libraries used from reading https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages

The following link shows how you could use ldd or objdump to list dynamic libs needed. https://stackoverflow.com/questions/5103443/how-to-check-what-shared-libraries-are-loaded-at-run-time-for-a-given-process

The info at https://github.com/AppImage/AppImageKit/wiki/Extracting-AppImages might be useful to allow people to swap out bits of the appimage for testing purposes without redownloading the entire thing.

It might also be useful to have a more light-weight or bare bones version 'agent', maybe written as a CLI application (or several small specialized ones)? For testing, one could then just download the latest version of, say, uhk-fw-uploader and see if that works. And in the long term, it might help with scripting things, or not needing to run the full gui just to have the proxy function running.

**Comment by mondalaci** [comment]
@luteijn Electron builder doesn't only build AppImages, but also snaps and who knows what in the future. Static linking seems the easiest and most reliable way forward.

A CLI Agent version would introduce additional mainteance burden which is already crazy given that Agent runs on all the 3 major OSes and has an Electron and web version. We can't afford more overhead.

**Comment by IzK666** [comment]
After downgrading the keyboard to v8.2.2 with debian, I've tested the new static blhost in Agent 1.2.3 with puppy linux and works fine! :)
Upgraded succesfully to 8.2.5 both halves.

Thank you, @mondalaci and @luteijn (for the guide to extract the appImage)

**Comment by mondalaci** [comment]
Thank you so much, everybody! This was real teamwork, and I'm delighted that blhost finally works on all Linux distros. I've just released Agent 1.2.4 which includes the new static Linux blhost version.

According to the above, chances are good that blhost works well on both Linux and Windows, but the OSX version still segfaults on some machines. Do you happen to know someone who can reproduce the issue and possibly build blhost on OSX? Wink, wink @spuder :)

**Comment by spuder** [comment]
I updated to the latest agent. 1.2.4

blhost shows a new timestamp and a different file size so it appears to have been updated. 

```
ls -ial "/Applications/UHK Agent.app/Contents/Resources/packages/blhost/mac/blhost"
15298749 -rwxr-xr-x@ 1 sowen  admin  695936 Jun 21 10:32 /Applications/UHK Agent.app/Contents/Resources/packages/blhost/mac/blhost
```

I'm still getting blhost failures 

```
Start flashing firmware
[11:04:04.880] [UhkOperations] Operating system: Darwin 17.5.0 x64
[11:04:04.881] [UhkOperations] Start flashing right firmware
[11:04:04.881] [UhkHidDevice] Start reenumeration, mode: Bootloader
[11:04:05.006] [UhkHidDevice] Available devices:
[11:04:05.006] {"vendorId":1452,"productId":610,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS12@14400000/Apple Internal Keyboard / Trackpad@14400000/Apple Internal Keyboard@0/AppleUSBTCKeyboard@14400000,0","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":549,"interface":-1,"usagePage":1,"usage":6}
[11:04:05.006] {"vendorId":1133,"productId":50475,"path":"IOService:/IOResources/AppleUSBHostResources/AppleUSBLegacyRoot/AppleUSBXHCI@14000000/USB Receiver@14200000/AppleUSBInterface@2/Logitech Unifying Interface","serialNumber":"","manufacturer":"Logitech","product":"USB Receiver","release":4611,"interface":-1,"usagePage":65280,"usage":1}
[11:04:05.007] {"vendorId":1133,"productId":50475,"path":"IOService:/IOResources/AppleUSBHostResources/AppleUSBLegacyRoot/AppleUSBXHCI@14000000/USB Receiver@14200000/AppleUSBInterface@1/Logitech Mouse Interface","serialNumber":"","manufacturer":"Logitech","product":"USB Receiver","release":4611,"interface":-1,"usagePage":1,"usage":2}
[11:04:05.007] {"vendorId":1133,"productId":50475,"path":"IOService:/IOResources/AppleUSBHostResources/AppleUSBLegacyRoot/AppleUSBXHCI@14000000/USB Receiver@14200000/AppleUSBInterface@0/Logitech Keyboard Interface","serialNumber":"","manufacturer":"Logitech","product":"USB Receiver","release":4611,"interface":-1,"usagePage":1,"usage":6}
[11:04:05.007] {"vendorId":1452,"productId":610,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS12@14400000/Apple Internal Keyboard / Trackpad@14400000/Touchpad@2/AppleUSBTCButtons@14400000,2","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":549,"interface":-1,"usagePage":1,"usage":2}
[11:04:05.007] {"vendorId":1452,"productId":610,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS12@14400000/Apple Internal Keyboard / Trackpad@14400000/Touchpad@1/AppleUSBMultitouchDriver@14400000,1","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":549,"interface":-1,"usagePage":65280,"usage":1}
[11:04:05.007] {"vendorId":2385,"productId":5796,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG1@1,1/IOPP/UPSB@0/IOPP/DSB1@3/IOPP/UPS0@0/IOPP/pci-bridge@0/IOPP/pci1b73,1100@0/AppleUSBXHCIFL1100@00000000/AppleUSB20XHCIPort@00200000/HyperX 7.1 Audio@00200000/IOUSBHostInterface@3/IOUSBHostHIDDevice@00200000,3","serialNumber":"00000000","manufacturer":"Kingston","product":"HyperX 7.1 Audio","release":5,"interface":-1,"usagePage":12,"usage":1}
[11:04:05.007] {"vendorId":3468,"productId":314,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG1@1,1/IOPP/UPSB@0/IOPP/DSB1@3/IOPP/UPS0@0/IOPP/pci-bridge@0/IOPP/pci1b73,1100@0/AppleUSBXHCIFL1100@00000000/AppleUSB20XHCIPort@00300000/USB PnP Sound Device@00300000/IOUSBHostInterface@3/IOUSBHostHIDDevice@00300000,3","serialNumber":"","manufacturer":"C-Media Electronics Inc.      ","product":"USB PnP Sound Device","release":256,"interface":-1,"usagePage":12,"usage":1}
[11:04:05.007] {"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG1@1,1/IOPP/UPSB@0/IOPP/DSB1@3/IOPP/UPS0@0/IOPP/pci-bridge@0/IOPP/pci1b73,1100@0/AppleUSBXHCIFL1100@00000000/AppleUSB20XHCIPort@00400000/USB2.0 Hub@00400000/AppleUSB20Hub@00400000/AppleUSB20HubPort@00420000/Ultimate Hacking Keyboard@00420000/IOUSBHostInterface@3/IOUSBHostHIDDevice@00420000,3","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":-1,"usagePage":1,"usage":128}
[11:04:05.008] {"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG1@1,1/IOPP/UPSB@0/IOPP/DSB1@3/IOPP/UPS0@0/IOPP/pci-bridge@0/IOPP/pci1b73,1100@0/AppleUSBXHCIFL1100@00000000/AppleUSB20XHCIPort@00400000/USB2.0 Hub@00400000/AppleUSB20Hub@00400000/AppleUSB20HubPort@00420000/Ultimate Hacking Keyboard@00420000/IOUSBHostInterface@2/IOUSBHostHIDDevice@00420000,2","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":-1,"usagePage":12,"usage":1}
[11:04:05.008] {"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG1@1,1/IOPP/UPSB@0/IOPP/DSB1@3/IOPP/UPS0@0/IOPP/pci-bridge@0/IOPP/pci1b73,1100@0/AppleUSBXHCIFL1100@00000000/AppleUSB20XHCIPort@00400000/USB2.0 Hub@00400000/AppleUSB20Hub@00400000/AppleUSB20HubPort@00420000/Ultimate Hacking Keyboard@00420000/IOUSBHostInterface@1/IOUSBHostHIDDevice@00420000,1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":-1,"usagePage":1,"usage":6}
[11:04:05.008] {"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG1@1,1/IOPP/UPSB@0/IOPP/DSB1@3/IOPP/UPS0@0/IOPP/pci-bridge@0/IOPP/pci1b73,1100@0/AppleUSBXHCIFL1100@00000000/AppleUSB20XHCIPort@00400000/USB2.0 Hub@00400000/AppleUSB20Hub@00400000/AppleUSB20HubPort@00420000/Ultimate Hacking Keyboard@00420000/IOUSBHostInterface@0/IOUSBHostHIDDevice@00420000,0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":-1,"usagePage":65280,"usage":1}
[11:04:05.008] {"vendorId":1133,"productId":4133,"path":"IOService:/IOResources/AppleUSBHostResources/AppleUSBLegacyRoot/AppleUSBXHCI@14000000/USB Receiver@14200000/Logitech Unifying Network/Logitech Unifying Device@1","serialNumber":"","manufacturer":"Logitech","product":"Unifying Device","release":4611,"interface":-1,"usagePage":1,"usage":2}
[11:04:05.008] {"vendorId":1452,"productId":65535,"path":"IOService:/IOResources/AppleUSBHostResources/AppleUSBLegacyRoot/AppleUSBXHCI@14000000/USB Receiver@14200000/Logitech Unifying Network/Logitech Unifying Device@1/Logitech HID Event Service/com_Logitech_HISpecialKeys/IOHIDKeyboardEventDevice","serialNumber":"","manufacturer":"Apple","product":"Unifying Device","release":4611,"interface":-1,"usagePage":1,"usage":6}
[11:04:05.008] {"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG1@1,1/IOPP/UPSB@0/IOPP/DSB1@3/IOPP/UPS0@0/IOPP/pci-bridge@0/IOPP/pci1b73,1100@0/AppleUSBXHCIFL1100@00000000/AppleUSB20XHCIPort@00400000/USB2.0 Hub@00400000/AppleUSB20Hub@00400000/AppleUSB20HubPort@00420000/Ultimate Hacking Keyboard@00420000/IOUSBHostInterface@4/IOUSBHostHIDDevice@00420000,4","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":-1,"usagePage":1,"usage":2}
[11:04:05.008] {"vendorId":1452,"productId":65535,"path":"IOService:/IOResources/AppleUSBHostResources/AppleUSBLegacyRoot/AppleUSBXHCI@14000000/USB Receiver@14200000/Logitech Unifying Network/Logitech Unifying Device@1/Logitech HID Event Service/com_Logitech_HIKeyboard/IOHIDKeyboardEventDevice","serialNumber":"","manufacturer":"Apple","product":"Unifying Device","release":4611,"interface":-1,"usagePage":1,"usage":6}
[11:04:05.010] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG1@1,1/IOPP/UPSB@0/IOPP/DSB1@3/IOPP/UPS0@0/IOPP/pci-bridge@0/IOPP/pci1b73,1100@0/AppleUSBXHCIFL1100@00000000/AppleUSB20XHCIPort@00400000/USB2.0 Hub@00400000/AppleUSB20Hub@00400000/AppleUSB20HubPort@00420000/Ultimate Hacking Keyboard@00420000/IOUSBHostInterface@0/IOUSBHostHIDDevice@00420000,0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":-1,"usagePage":65280,"usage":1}
[11:04:05.010] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[11:04:05.010] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[11:04:05.593] [UhkHidDevice] reenumeration devices up
[11:04:05.593] [UhkHidDevice] Device communication closing.
[11:04:05.593] [UhkHidDevice] Device communication closed.
[11:04:05.594] [blhost] RUN: /Applications/UHK Agent.app/Contents/Resources/packages/blhost/mac/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[11:04:05.620] [blhost] EXIT_CODE: null
[11:04:05.620] [blhost] FINISHED: null
[11:04:05.827] [DeviceService] updateFirmware error { message: 'blhost error code:null',
  stack: 'Error: blhost error code:null\n    at finish (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:53:35)\n    at ChildProcess.childProcess.on.code (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:36:17)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' }
[11:04:05.835] [UhkHidDevice] Available devices:
[11:04:05.835] {"vendorId":1133,"productId":50475,"path":"IOService:/IOResources/AppleUSBHostResources/AppleUSBLegacyRoot/AppleUSBXHCI@14000000/USB Receiver@14200000/AppleUSBInterface@0/Logitech Keyboard Interface","serialNumber":"","manufacturer":"Logitech","product":"USB Receiver","release":4611,"interface":-1,"usagePage":1,"usage":6}
[11:04:05.836] {"vendorId":1133,"productId":50475,"path":"IOService:/IOResources/AppleUSBHostResources/AppleUSBLegacyRoot/AppleUSBXHCI@14000000/USB Receiver@14200000/AppleUSBInterface@2/Logitech Unifying Interface","serialNumber":"","manufacturer":"Logitech","product":"USB Receiver","release":4611,"interface":-1,"usagePage":65280,"usage":1}
[11:04:05.836] {"vendorId":1133,"productId":50475,"path":"IOService:/IOResources/AppleUSBHostResources/AppleUSBLegacyRoot/AppleUSBXHCI@14000000/USB Receiver@14200000/AppleUSBInterface@1/Logitech Mouse Interface","serialNumber":"","manufacturer":"Logitech","product":"USB Receiver","release":4611,"interface":-1,"usagePage":1,"usage":2}
[11:04:05.836] {"vendorId":2385,"productId":5796,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG1@1,1/IOPP/UPSB@0/IOPP/DSB1@3/IOPP/UPS0@0/IOPP/pci-bridge@0/IOPP/pci1b73,1100@0/AppleUSBXHCIFL1100@00000000/AppleUSB20XHCIPort@00200000/HyperX 7.1 Audio@00200000/IOUSBHostInterface@3/IOUSBHostHIDDevice@00200000,3","serialNumber":"00000000","manufacturer":"Kingston","product":"HyperX 7.1 Audio","release":5,"interface":-1,"usagePage":12,"usage":1}
[11:04:05.836] {"vendorId":1452,"productId":65535,"path":"IOService:/IOResources/AppleUSBHostResources/AppleUSBLegacyRoot/AppleUSBXHCI@14000000/USB Receiver@14200000/Logitech Unifying Network/Logitech Unifying Device@1/Logitech HID Event Service/com_Logitech_HIKeyboard/IOHIDKeyboardEventDevice","serialNumber":"","manufacturer":"Apple","product":"Unifying Device","release":4611,"interface":-1,"usagePage":1,"usage":6}
[11:04:05.836] {"vendorId":1452,"productId":610,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS12@14400000/Apple Internal Keyboard / Trackpad@14400000/Touchpad@1/AppleUSBMultitouchDriver@14400000,1","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":549,"interface":-1,"usagePage":65280,"usage":1}
[11:04:05.836] {"vendorId":3468,"productId":314,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG1@1,1/IOPP/UPSB@0/IOPP/DSB1@3/IOPP/UPS0@0/IOPP/pci-bridge@0/IOPP/pci1b73,1100@0/AppleUSBXHCIFL1100@00000000/AppleUSB20XHCIPort@00300000/USB PnP Sound Device@00300000/IOUSBHostInterface@3/IOUSBHostHIDDevice@00300000,3","serialNumber":"","manufacturer":"C-Media Electronics Inc.      ","product":"USB PnP Sound Device","release":256,"interface":-1,"usagePage":12,"usage":1}
[11:04:05.836] {"vendorId":1452,"productId":610,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS12@14400000/Apple Internal Keyboard / Trackpad@14400000/Touchpad@2/AppleUSBTCButtons@14400000,2","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":549,"interface":-1,"usagePage":1,"usage":2}
[11:04:05.837] {"vendorId":1133,"productId":4133,"path":"IOService:/IOResources/AppleUSBHostResources/AppleUSBLegacyRoot/AppleUSBXHCI@14000000/USB Receiver@14200000/Logitech Unifying Network/Logitech Unifying Device@1","serialNumber":"","manufacturer":"Logitech","product":"Unifying Device","release":4611,"interface":-1,"usagePage":1,"usage":2}
[11:04:05.837] {"vendorId":7504,"productId":24864,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG1@1,1/IOPP/UPSB@0/IOPP/DSB1@3/IOPP/UPS0@0/IOPP/pci-bridge@0/IOPP/pci1b73,1100@0/AppleUSBXHCIFL1100@00000000/AppleUSB20XHCIPort@00400000/USB2.0 Hub@00400000/AppleUSB20Hub@00400000/AppleUSB20HubPort@00420000/UHK Bootloader@00420000/MCU HID GENERIC DEVICE@0/IOUSBHostHIDDevice@00420000,0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":-1,"usagePage":65280,"usage":1}
[11:04:05.837] {"vendorId":1452,"productId":610,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS12@14400000/Apple Internal Keyboard / Trackpad@14400000/Apple Internal Keyboard@0/AppleUSBTCKeyboard@14400000,0","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":549,"interface":-1,"usagePage":1,"usage":6}
[11:04:05.837] {"vendorId":1452,"productId":65535,"path":"IOService:/IOResources/AppleUSBHostResources/AppleUSBLegacyRoot/AppleUSBXHCI@14000000/USB Receiver@14200000/Logitech Unifying Network/Logitech Unifying Device@1/Logitech HID Event Service/com_Logitech_HISpecialKeys/IOHIDKeyboardEventDevice","serialNumber":"","manufacturer":"Apple","product":"Unifying Device","release":4611,"interface":-1,"usagePage":1,"usage":6}
[11:04:05.838] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected
    at Promise (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:92:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:89:1)
    at Generator.next (<anonymous>)
    at /Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.write (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:88:1)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:133:1)
    at Generator.next (<anonymous>)

[11:04:05.839] [blhost] CLOSE_CODE: null
[11:04:06.354] [DeviceService] Device connection state changed to: { bootloaderActive: true, connected: false, hasPermission: true }
blhost error code:null

```

**Comment by spuder** [comment]
I've been testing every combination of usb hub, and cables to reproduce the issue. I can confidently say that the culprit is my logitech usb receiver. With it plugged in, the flashing fails 100% of the time. With it unplugged the flash is succesful 100% of the time. Does not matter where the logitech receiver is plugged in (usb hub, right usb port, left usb port), it always causes failure. 
![screenshot 2018-06-25 11 36 07](https://user-images.githubusercontent.com/242382/41866032-306f436c-786c-11e8-8fde-86157a7b3502.png)
![img_6448](https://user-images.githubusercontent.com/242382/41866093-5fcdfffe-786c-11e8-9951-9c2edb38ae6c.jpg)

**Comment by kareltucek** [comment]
1.2.4 fails on my linux. (1.2.3 and 1.2.2 both work fine.) 

Regarding the receiver, I am using standard logitech unifying receiver (in the same hub as UHK), but I do not observe any correlation here (i.e., 1.2.2 worked fine even with receiver, 1.2.4 does not work either way; disconnecting hub makes no difference)).

`Start flashing firmware
[19:35:28.095] [UhkOperations] Operating system: Linux 4.16.13-2-ARCH x64
[19:35:28.099] [UhkOperations] Start flashing right firmware
[19:35:28.101] [UhkHidDevice] Start reenumeration, mode: Bootloader
[19:35:28.222] [UhkHidDevice] Available devices:
[19:35:28.225] {"vendorId":7504,"productId":24866,"path":"0001:0012:00","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
[19:35:28.226] {"vendorId":7504,"productId":24866,"path":"0001:0012:01","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":1}
[19:35:28.227] {"vendorId":7504,"productId":24866,"path":"0001:0012:02","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":2}
[19:35:28.228] {"vendorId":7504,"productId":24866,"path":"0001:0012:03","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":3}
[19:35:28.230] {"vendorId":7504,"productId":24866,"path":"0001:0012:04","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":4}
[19:35:28.231] {"vendorId":1133,"productId":50475,"path":"0001:000c:00","release":4609,"interface":0}
[19:35:28.232] {"vendorId":1133,"productId":50475,"path":"0001:000c:01","release":4609,"interface":1}
[19:35:28.232] {"vendorId":1133,"productId":50475,"path":"0001:000c:02","release":4609,"interface":2}
[19:35:28.233] {"vendorId":1386,"productId":828,"path":"0001:000e:00","release":256,"interface":0}
[19:35:28.234] {"vendorId":1386,"productId":828,"path":"0001:000e:01","release":256,"interface":1}
[19:35:28.234] {"vendorId":1386,"productId":828,"path":"0001:000e:02","release":256,"interface":2}
[19:35:28.236] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"0001:0012:00","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
[19:35:28.237] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[19:35:28.238] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[19:35:29.006] [UhkHidDevice] reenumeration devices up
[19:35:29.009] [UhkHidDevice] Device communication closing.
[19:35:29.010] [UhkHidDevice] Device communication closed.
[19:35:29.013] [blhost] RUN: /tmp/.mount_UHK.AgQhlgkr/app/resources/packages/blhost/linux/x86_64/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[19:35:29.442] [blhost] EXIT_CODE: null
[19:35:29.444] [blhost] FINISHED: null
[19:35:30.222] [DeviceService] updateFirmware error { message: 'blhost error code:null',
  stack: 'Error: blhost error code:null\n    at finish (/tmp/.mount_UHK.AgQhlgkr/app/resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:53:35)\n    at ChildProcess.childProcess.on.code (/tmp/.mount_UHK.AgQhlgkr/app/resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:36:17)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' }
[19:35:30.228] [UhkHidDevice] Available devices:
[19:35:30.229] {"vendorId":7504,"productId":24864,"path":"0001:0013:00","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":0}
[19:35:30.229] {"vendorId":1133,"productId":50475,"path":"0001:000c:00","release":4609,"interface":0}
[19:35:30.230] {"vendorId":1133,"productId":50475,"path":"0001:000c:01","release":4609,"interface":1}
[19:35:30.231] {"vendorId":1133,"productId":50475,"path":"0001:000c:02","release":4609,"interface":2}
[19:35:30.232] {"vendorId":1386,"productId":828,"path":"0001:000e:00","release":256,"interface":0}
[19:35:30.232] {"vendorId":1386,"productId":828,"path":"0001:000e:01","release":256,"interface":1}
[19:35:30.234] {"vendorId":1386,"productId":828,"path":"0001:000e:02","release":256,"interface":2}
[19:35:30.236] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected
    at Promise (/tmp/.mount_UHK.AgQhlgkr/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:92:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgQhlgkr/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:89:1)
    at Generator.next (<anonymous>)
    at /tmp/.mount_UHK.AgQhlgkr/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/tmp/.mount_UHK.AgQhlgkr/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.write (/tmp/.mount_UHK.AgQhlgkr/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:88:1)
    at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgQhlgkr/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:133:1)
    at Generator.next (<anonymous>)

[19:35:30.243] [blhost] CLOSE_CODE: null
[19:35:30.752] [DeviceService] Device connection state changed to: { bootloaderActive: true, connected: false, hasPermission: true }
blhost error code:null
`

**Comment by spuder** [comment]
I've tried running blhost directly

```
sudo ./blhost -u -- get-property 1
Password:
Segmentation fault: 11
```

When I disconnect the logitech device it no longer crashes

```
sudo ./blhost -u -- get-property 1
Error: UsbHidPeripheral() cannot open USB HID device (vid=0x15a2, pid=0x0073, sn=).
```

It seems related to this thread: https://community.nxp.com/thread/453944

**Comment by mondalaci** [comment]
@spuder Thanks for your feedback! The USB related issues that revolve around firmware updates in general and blhost in specific never cease to amaze me. We'll highlight the importance of unplugging other USB devices when firmware update fails by implementing #700.

@kareltucek Apparently, we can't pick one blhost version over the other, so we'll fall back by implementing #701.

**Comment by luteijn** [comment]
for me, blhost-old works fine, the statically linked blhost from agent 1.2.4 just gets killed because of  "Illegal instruction" (exit code 132).

By basically following the steps at https://stackoverflow.com/questions/10354147/find-which-assembly-instruction-caused-an-illegal-instruction-error-without-debug (except I just ran blhost via gdb directly instead of using a dumped core) it seems the illegal instruction is a 'shrx'. A 'new' instruction that is not supported on older cpus according to https://github.com/DragonFlyBSD/DPorts/issues/79  ; that issue and https://github.com/gbevin/SendMIDI/issues/4 have some suggestions on compiler flags to use to generate less specialized code that might run on more machines.

**Comment by mondalaci** [comment]
@luteijn Thank you! Yours is very valuable insight. It would be great to use a single blhost binary that works across platforms.

@iprok Would you possibly build yet another blhost? This time also statically linked but without special instructions.

**Comment by mondalaci** [comment]
@iprok I hate to bug you with this, but I'm afraid that many users will hit this issue, and for some reason my gcc doesn't build a blhost as reliable as the one you built. My hope is that it only takes one more build which should work on every Linux distros. If you get to it, please do share the exact command you used to build blhost. Thanks so much in advance!

**Comment by iprok** [comment]
I was sure I've uploaded it. Have built version with mtune=generic after your previous message. I'm attaching it to this message.

[blhost-mtune-general.gz](https://github.com/UltimateHackingKeyboard/agent/files/2169812/blhost-mtune-general.gz)

**Comment by mondalaci** [comment]
@iprok Thanks so much! Would you please provide the full command line including `make`, the static flag, and anything else you used?

@kareltucek @IzK666 Would you please test `blhost-mtune-general`? If it works for both of you then chances are it's the real deal.

**Comment by kareltucek** [comment]
@mondalaci you mean the one uploaded by iprok right? When simply executed without any arguments, it crashes with illegal instruction. Namely

	0x59e52b        shrx   %rdi,-0x10(%rax),%rdx

**Comment by iprok** [comment]
@kareltucek give me please output of:
1) `uname -a`
2) `gcc --version`

Also tell me please your distro name, distro version and ideally glibc version.

**Comment by kareltucek** [comment]
$ uname -a
    Linux zotac 4.16.13-2-ARCH #1 SMP PREEMPT Fri Jun 1 18:46:11 UTC 2018 x86_64 GNU/Linux

    $ gcc --version
    gcc (GCC) 8.1.1 20180531
    Copyright (C) 2018 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by kareltucek** [comment]
Architecture:        x86_64
	CPU op-mode(s):      32-bit, 64-bit
	Byte Order:          Little Endian
	CPU(s):              4
	On-line CPU(s) list: 0-3
	Thread(s) per core:  1
	Core(s) per socket:  4
	Socket(s):           1
	NUMA node(s):        1
	Vendor ID:           GenuineIntel
	CPU family:          6
	Model:               76
	Model name:          Intel(R) Celeron(R) CPU  N3150  @ 1.60GHz
	Stepping:            3
	CPU MHz:             2081.419
	CPU max MHz:         2080.0000
	CPU min MHz:         480.0000
	BogoMIPS:            3201.33
	Virtualization:      VT-x
	L1d cache:           24K
	L1i cache:           32K
	L2 cache:            1024K
	NUMA node0 CPU(s):   0-3
	Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes rdrand lahf_lm 3dnowprefetch epb pti tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat

**Comment by iprok** [comment]
I have located the problem. My CPU has AVX instruction set and yours not. I don't know how to turn it off exactly so I need few tries. Please try attached version.
[blhost-mtune-evenmoregeneral.gz](https://github.com/UltimateHackingKeyboard/agent/files/2170741/blhost-mtune-evenmoregeneral.gz)

**Comment by kareltucek** [comment]
crashed

**Comment by kareltucek** [comment]
I guess including -march=x86_64 should do. (If there is a simple way to set things up on my machine, I could probably play with it a bit myself or give you remote access.)

**Comment by iprok** [comment]
Oh, I think that all my system with statically included libraries (libgcc, libc and so on) are built with march=native. I will try to build on old debian, not gentoo. Be right back in few minutes. By the way you can connect me directly using xmpp or email ivan at prokudin dot org

**Comment by iprok** [comment]
@mondalaci I have tried to compile under the oldest OS I have, it's Debian Wheezy. I have to make some more changes to Makefile , here they are https://github.com/iprok/bootloader/tree/makeitstatic . And the attached version works for @kareltucek as he have told me by email. And for me too on all my linuxes.
[blhost-debian.gz](https://github.com/UltimateHackingKeyboard/agent/files/2170906/blhost-debian.gz)

**Comment by kareltucek** [comment]
btw regarding architectures... Is there a reason why the linux AppImage is 64 bit specific and why there are separate 32/64 blhosts included in the AppImage? I would expect 32bit version of agent to be sufficient. (And in that case we clearly want march=core2, not x86_64) 

(I don't care much for detailed explanation - just thinking if these observations could simplify things for @mondalaci )

**Comment by mondalaci** [comment]
@iprok Thanks so much for your contribution! It's very encouraging to hear that the new blhost build works everywhere so far. Do you want to send a PR for the bootloader repo, or would you rather want me to apply the changes myself? Please let me know.

@kareltucek I'm not sure why we originally included different architecture-specific Linux builds of blhost into Agent, but I'm sure that only the x86-64 Linux build is used by Agent. As for the AppImage, I think electron-builder is simply configured to produce x86-64 Agent builds for Linux. So far, nobody has complained about this. Chances are x86-32 is so heavily phased out that nobody uses it.

@IzK666 Would you please give a try to the most recent blhost version? I'd like to be sure that it works on your side, too.

**Comment by mondalaci** [comment]
@IzK666 Would you please also test the even more recent blhost-debian? I'd like to include this version into the upcoming Agent release.

**Comment by IzK666** [comment]
Yeah! It works too. :)

**Comment by mondalaci** [comment]
@IzK666 Excellent, thank you! Just committed blhost-debian to master in eb0daadf98b6af15cafbe7a973832dd70ce74349. I really do hope that this solves the issue going forward.
