### ISSUE TITLE
Agent hanging/stalled on `Loading Keyboard Configuration`

### ISSUE THREAD

**Issue by paran01d** [UltimateHackingKeyboard/agent#711]
Just got my UHK and am attempting to run agent, build process of tag v1.2.5 worked fine on ubuntu 17.10 once I specifically install libusb-1.0.0-dev, but when I launch agent it seems to get stuck on a `Loading Keyboard Configuration.. please hang tight` screen.

I enclose the output from npm run electron. nothing further appears in this log while its waiting for config.

`npm run electron

> uhk-agent@1.2.5 electron /home/paran01d/Projects/agent
> lerna exec --scope uhk-agent npm start

lerna info version 2.9.0
lerna info scope uhk-agent

> uhk-agent@0.0.0 start /home/paran01d/Projects/agent/packages/uhk-agent
> electron ./dist/electron-main.js

[14:58:36.121] [info] [Electron Main] Create new window.
[14:58:36.130] [info] [Electron Main] packagesDir: /home/paran01d/Projects/agent/tmp
[14:58:36.204] [info] [DeviceService] Device connection state changed to: { bootloaderActive: false, connected: true, hasPermission: true }
[14:58:36.211] [debug] [DeviceService] init success
[14:58:36.212] [info] [AppUpdateService] init success
[14:58:36.213] [info] [AppService] init success
[14:58:36.213] [info] [SudoService] App root dir:  /home/paran01d/Projects/agent/
[14:58:37.749] [info] [ '[AppRendererService] init success ' ]
[14:58:37.760] [info] [ '[DeviceRendererService] init success ' ]
[14:58:37.764] [info] [ 'Renderer appStart effect start' ]
[14:58:37.765] [debug] [AppUpdateService] check for update at startup: { checkForUpdate: false,
  autoUpdateSettings: { checkForUpdateOnStartUp: false, usePreReleaseUpdate: false } }
[14:58:37.766] [info] [ '[AppRendererService] getAppStartInfo' ]
[14:58:37.769] [info] [AppService] getAppStartInfo
[14:58:37.775] [info] [AppService] getAppStartInfo response: { commandLineArgs: { addons: false, layerDoubleTap: false },
  deviceConnected: true,
  hasPermission: true,
  bootloaderActive: false,
  platform: 'linux',
  osVersion: '4.13.0-45-generic' }
[14:58:37.776] [info] [ 'Renderer appStart effect end' ]
[14:58:37.842] [info] [ '[AppRendererService] dispatch action',
  ProcessAppStartInfoAction {
    payload: 
     { bootloaderActive: false,
       commandLineArgs: [Object],
       deviceConnected: true,
       hasPermission: true,
       osVersion: '4.13.0-45-generic',
       platform: 'linux' },
    type: '[app] process start info' } ]
[14:58:37.842] [debug] [ '[AppEffect][processStartInfo] payload:',
  { bootloaderActive: false,
    commandLineArgs: { addons: false, layerDoubleTap: false },
    deviceConnected: true,
    hasPermission: true,
    osVersion: '4.13.0-45-generic',
    platform: 'linux' } ]
[14:58:37.851] [debug] [UhkHidDevice] Available devices:
[14:58:37.851] [debug] {"vendorId":7119,"productId":5,"path":"0003:0006:00","release":20,"interface":0}
[14:58:37.851] [debug] {"vendorId":7504,"productId":24866,"path":"0003:0007:00","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
[14:58:37.851] [debug] {"vendorId":7504,"productId":24866,"path":"0003:0007:01","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":1}
[14:58:37.851] [debug] {"vendorId":7504,"productId":24866,"path":"0003:0007:02","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":2}
[14:58:37.852] [debug] {"vendorId":7504,"productId":24866,"path":"0003:0007:03","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":3}
[14:58:37.852] [debug] {"vendorId":7504,"productId":24866,"path":"0003:0007:04","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":4}
[14:58:37.852] [debug] {"vendorId":1267,"productId":8756,"path":"0001:0005:00","release":4369,"interface":0}
[14:58:37.853] [debug] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"0003:0007:00","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
[14:58:37.854] [debug] [UhkHidDevice] USB[W]: 09 
[14:58:37.861] [debug] [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[14:58:37.862] [debug] [UhkHidDevice] USB[W]: 09 
[14:58:37.869] [debug] [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[14:58:37.870] [debug] [DeviceOperation] USB[T]: Read ValidatedUserConfig size from keyboard
[14:58:37.871] [debug] [UhkHidDevice] USB[W]: 00 02 
[14:58:37.877] [debug] [UhkHidDevice] USB[R]: 00 40 00 c0 7f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[14:58:37.877] [debug] [UhkHidDevice] Device communication closing.
[14:58:37.887] [debug] [UhkHidDevice] Device communication closed.
[14:58:37.888] [debug] [DeviceOperation] User config size: 32704
[14:58:37.888] [debug] [DeviceOperation] getConfigSize() configSize: 32704
[14:58:37.888] [debug] [DeviceOperation] USB[T]: Read ValidatedUserConfig from keyboard
[14:58:37.895] [debug] [UhkHidDevice] Available devices unchanged
[14:58:37.896] [debug] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"0003:0007:00","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
[14:58:37.896] [debug] [UhkHidDevice] USB[W]: 04 02 3f 00 00`

**Comment by paran01d** [comment]
Just to confirm the same thing happens with the AppImage.

**Comment by mondalaci** [comment]
Please unplug every USB device, then only plug in your UHK and retry.

Assuming it succeeded, please add USB devices one by one and let me know which caused the issue.

**Comment by paran01d** [comment]
Ok Ive found it gets stuck when plugged into my Dell TB-16 dock.

https://www.dell.com/support/article/au/en/audhs1/sln301105/dell-thunderbolt-dock-tb16-information-and-specifications?lang=en

There are plenty of problems with this dock under linux, I should have guessed it was this myself. Let me know if there is anymore debug I can do if you feel its worth persuing. Also if you can point me in the right direction happy to try and fix myself.

**Comment by mondalaci** [comment]
USB hubs and docking stations seem to be a huge source of issues like this.

Would you try to flash the most recent https://github.com/UltimateHackingKeyboard/firmware/releases/tag/v8.3.3 firmware via Agent, then retry via you hub and let me know how it works?

Please don't forget to install the bundled firmware via Agent afterwards, as firmware 8.3.3 is not stable according to my testing.

**Comment by paran01d** [comment]
Sorry not had a chance to do this yet, will get to it as soon as I can.

**Comment by moschan** [comment]
I faced same issue on Mac.
I tried this (https://github.com/UltimateHackingKeyboard/agent/issues/711#issuecomment-401776712) solution and it immediately fixed.

Once I open the agen app corectly,  I can plug any device without problem.

Thank you! @mondalaci

**Comment by rightaditya** [comment]
@mondalaci I can help debug this---I've got the same issue. I'm using the 1.2.12 release of Agent and the 8.5.3 firmware release.

My setup is this: UHK + trackball + webcam into monitor's USB ports; monitor's USB to Dell TB-16 (along with ethernet and monitor via DisplayPort); Dell TB-16 to laptop via Thunderbolt.

Under Windows, everything works fine. Under Linux, Agent gets stuck on the Loading Keyboard Configuration screen. If I instead connect my monitor's USB directly to my laptop, Agent works fine. The UHK is still going through the monitor's USB hub in that case, but bypassing the Thunderbolt dock.

**Comment by mondalaci** [comment]
@rightaditya Thanks for the feedback! Please share your log that Agent outputs in the terminal.

**Comment by rightaditya** [comment]
[As requested.](https://github.com/UltimateHackingKeyboard/agent/files/2674643/agent.log)

**Comment by mondalaci** [comment]
@rightaditya Is this the log of your Linux computer on which Agent gets stuck?

**Comment by rightaditya** [comment]
@mondalaci Yeah. I started Agent and let it sit until I wasn't seeing anything else show up in the terminal. Closed Agent but the terminal didn't return to the shell right away so I had to Ctrl+C out.

**Comment by mondalaci** [comment]
@rightaditya USB communication clearly gets stuck based on your log. I think we should implement a watcher in Agent, and display a relevant instruction to the user to try to connect the UHK without a hub or docking station. Thanks for your help!

**Comment by mondalaci** [comment]
When USB communication gets stuck for 1 second, we'll display the following instead of "Hang tight!":

> USB communication got stuck! Please connect your UHK directly to your computer, and disconnect other USB devices.

**Comment by rightaditya** [comment]
@mondalaci Definitely a more informative message :) If I had the bandwidth I'd dig further to try and figure out if it can be made to work through a hub, but time is very short these days :(

**Comment by rightaditya** [comment]
@mondalaci So I just fired up Agent 1.3.2 and it was able to get past the initial screen and load my configs from the keyboard through my hubs! Unfortunately it couldn't save any changes. The terminal just printed:

> `[DeviceService] stop poll UHK Device`

And then got stuck. GUI was still responsive but there was no way for me to cancel the save attempt, and it wasn't timing out (or at least, my patience timed out first). After killing Agent once, I started it again and tried the firmware update to test, and had the same problem. After killing Agent again, now it won't load anything and gets stuck at the Hang Tight screen as before... :thinking:

**Comment by mondalaci** [comment]
@rightaditya This issue hasn't ever been reported yet. Please restart your computer and retry.

**Comment by mondalaci** [comment]
In light of #1176 and UltimateHackingKeyboard/firmware#269, when USB communication gets stuck for 1 second, let's display the following instead of "Hang tight!":

> USB communication got stuck! Please connect your UHK directly to your computer, and disconnect other USB devices.
>
> Using a Ryzen PC? Please try every USB port. Some ports should work with the UHK.

**Comment by rightaditya** [comment]
@mondalaci Sorry for how long it took me to get to testing properly!

I tested with both 1.3.2 and latest 1.4.2. I tested each immediately after rebooting. I'm on Ubuntu 18.04.4. My UHK is going through two hubs: first, it goes to my monitor (Dell U3415W), which then goes (via USB3 cable) to a thunderbolt dock (Dell TB-16), which then goes to my laptop.

If I remove the thunderbolt dock from the chain, and go straight from the monitor to the laptop, then 1.4.2 can connect to the keyboard just fine, and flash new firmware, etc.

With both docks in the chain, behaviour differs between 1.3.2 and 1.4.2. With 1.3.2, it can connect to the keyboard and read layouts, etc. from it, but if I try and make any changes or flash new firmware, it gets stuck as I mentioned above. 1.4.2 can't connect to the keyboard at all.

Given what I found further upthread, it looks like some change between 1.2.12 and 1.3.2 enabled Agent to read from (but not write to) the keyboard. Then with 1.4.2, the ability to read was lost again.

**Comment by mondalaci** [comment]
@rightaditya You're using the terms "hub" and "dock" interchangeably, even though they're quite different. Hubs use ASICs to implement the USB protocol and they usually follow the standard quite strictly. But docking stations usually use some sort of embedded OS which don't follow the USB protocol so strictly, hence such issues happen.

Please try to update the firmware of your docking station. I plan to find a USB expert to look to the bottom of such issues, but chances are these issues are due to external devices, and mainly due to docking stations. I appreciate your report, and sorry I can't provide a better solution for the time being.

**Comment by rightaditya** [comment]
@mondalaci Thanks a lot for clarifying that distinction! Indeed, I was using them interchangeably.

In my case, at least, I'm guessing that there is partially an OS issue involved, as I can upload new firmware (etc.) on Windows without issue going through both the monitor (a hub, I guess?) and dock. It's just on Ubuntu that things break. My dock firmware is indeed up-to-date. Dell does provide some Windows drivers for specific bits of the dock's functionality---one for audio, one for ethernet, and one for USB. Maybe there's some magic somewhere in there. Anecdotally, I _have_ found the dock to be more finicky on Linux.

I understand that there's not much to be done, especially in the circumstance of the problem being an OS one (except maybe waiting for a magic kernel update or something). It's not a problem; I don't fuss with my layout very much. I just thought I'd add some more detailed data.

I did become briefly excited that 1.3.2 could at least *read* from the UHK, even if it couldn't write to it, since 1.2.12 couldn't do that, and then intrigued that 1.4.2 regressed. I'd be happy to dig into it myself (to the extent that I can, not being a USB expert---as I obviously demonstrated 😏---and having no experience with anything in the kernel...) but have too much on my plate at the moment to take that on.

**Comment by mondalaci** [comment]
@rightaditya I'm pretty sure this is a largely a driver issue as Thunderbolt - USB protocol translation occurs which can mess things up.

If you want to diagnose this further then please use the latest 8.8.1 firmware and try out every Agent version to see exactly which versions exhibit regressions. Also, give multiple tries to every Agent version to make sure this issue can be deterministically reproduced.

**Comment by mondalaci** [comment]
Chances are good this issue has been resolved in Agent 1.4.3. Please give it a try guys, and follow up. I'll reopen this issue if needed.

**Comment by rightaditya** [comment]
Hmmm, things get a little further along with 1.4.3, but it still doesn't get through to the main Agent UI to show me the layouts, etc. I am on firmware 8.8.1 (and it works fine if I skip the dock).

With 1.4.3, I first saw this message while Agent was loading:
![image](https://user-images.githubusercontent.com/1624945/76245500-6617f180-6212-11ea-8eca-70be15f8b60c.png)
Then on subsequent attempts, instead I got:
![image](https://user-images.githubusercontent.com/1624945/76245582-86e04700-6212-11ea-8015-9a5958e4c637.png)

And here's the log from the terminal (I closed the window manually after a little bit):

```
> 14:30:17.331 › [Electron Main] Create new window.
> 14:30:17.338 › [Electron Main] packagesDir: /tmp/.mount_UHK.AgxpokXu/resources
> 14:30:17.339 › [WindowState] load settings
> 14:30:17.340 › [WindowState] loaded settings {
>   x: 1618,
>   y: 594,
>   width: 1463,
>   height: 846,
>   isMaximized: false,
>   isFullScreen: false
> }
> 14:30:17.342 › [WindowState] loaded settings is visible true
> 14:30:17.342 › [WindowState] return with loaded settings
> 14:30:17.505 › [DeviceService] start poll UHK Device
> 14:30:17.534 › [UhkHidDevice] Devices before checking permission:
> 14:30:17.539 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
> 14:30:17.540 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":1}
> 14:30:17.540 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw2","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":2}
> 14:30:17.540 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw3","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":3}
> 14:30:17.541 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw4","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":4}
> 14:30:17.541 › {"vendorId":1149,"productId":32792,"path":"/dev/hidraw5","serialNumber":"","manufacturer":"Kensington","product":"Expert Wireless TB","release":258,"interface":0}
> 14:30:17.541 › {"vendorId":1149,"productId":32792,"path":"/dev/hidraw6","serialNumber":"","manufacturer":"Kensington","product":"Expert Wireless TB","release":258,"interface":1}
> 14:30:17.542 › {"vendorId":1105,"productId":51713,"path":"/dev/hidraw7","serialNumber":"\b\b\b\b\u0004\u0004\u0004\u0004","manufacturer":"Texas Instruments","product":"Texas Instruments USBtoI2C Solution","release":256,"interface":0}
> 14:30:17.605 › [DeviceService] init success
> 14:30:17.606 › [AppUpdateService] init success
> 14:30:17.607 › [AppService] init success
> 14:30:17.607 › [SudoService] App root dir:  /tmp/.mount_UHK.AgxpokXu/resources
> 14:30:17.674 › [UhkHidDevice] Available devices:
> 14:30:17.675 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
> 14:30:17.677 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":1}
> 14:30:17.678 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw2","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":2}
> 14:30:17.679 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw3","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":3}
> 14:30:17.680 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw4","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":4}
> 14:30:17.680 › {"vendorId":1149,"productId":32792,"path":"/dev/hidraw5","serialNumber":"","manufacturer":"Kensington","product":"Expert Wireless TB","release":258,"interface":0}
> 14:30:17.681 › {"vendorId":1149,"productId":32792,"path":"/dev/hidraw6","serialNumber":"","manufacturer":"Kensington","product":"Expert Wireless TB","release":258,"interface":1}
> 14:30:17.681 › {"vendorId":1105,"productId":51713,"path":"/dev/hidraw7","serialNumber":"\b\b\b\b\u0004\u0004\u0004\u0004","manufacturer":"Texas Instruments","product":"Texas Instruments USBtoI2C Solution","release":256,"interface":0}
> 14:30:17.743 › [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"/dev/hidraw0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
> 14:30:17.744 › [UhkHidDevice] USB[W]: 09 
> 14:30:17.752 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:17.752 › [DeviceService] Device connection state changed to: {
>   bootloaderActive: false,
>   connected: true,
>   zeroInterfaceAvailable: true,
>   hasPermission: true,
>   udevRulesInfo: 'Ok',
>   halvesInfo: { areHalvesMerged: false, isLeftHalfConnected: true }
> }
> 14:30:18.011 › [UhkHidDevice] USB[W]: 09 
> 14:30:18.019 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:18.275 › [UhkHidDevice] USB[W]: 09 
> 14:30:18.284 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:18.339 › [AppUpdateService] check for update at startup: { checkForUpdateOnStartUp: true }
> 14:30:18.340 › [AppUpdateService] app started. Automatically check for update.
> 14:30:18.341 › firstRunVersion: 1.4.3
> 14:30:18.341 › package.version: 1.4.3
> 14:30:18.341 › Checking for update
> 14:30:18.342 › [AppUpdateService] checking for update
> 14:30:18.342 › sendIpcToWindow: checking-for-update undefined
> 14:30:18.349 › [AppService] getAppStartInfo
> 14:30:18.356 › [UhkHidDevice] USB[W]: 09 
> 14:30:18.363 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:18.370 › [AppService] getAppStartInfo response: {
>   deviceConnectionState: {
>     bootloaderActive: false,
>     connected: true,
>     zeroInterfaceAvailable: true,
>     hasPermission: true,
>     udevRulesInfo: 'Ok',
>     halvesInfo: { areHalvesMerged: false, isLeftHalfConnected: true }
>   },
>   commandLineArgs: { modules: false },
>   platform: 'linux',
>   osVersion: '5.3.0-40-generic',
>   udevFileContent: '# Ultimate Hacking Keyboard rules\n# These are the udev rules for ' +
>     'accessing the USB interfaces of the UHK as non-root users.\n# Copy this ' +
>     'file to /etc/udev/rules.d and physically reconnect the UHK afterwards.\n' +
>     'SUBSYSTEM=="input", ATTRS{idVendor}=="1d50", ' +
>     'ATTRS{idProduct}=="612[0-7]", GROUP="input", MODE="0660"\n' +
>     'SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ' +
>     'ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"\nKERNEL=="hidraw*", ' +
>     'ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"\n'
> }
> 14:30:18.480 › [DeviceService] stop poll UHK Device
> 14:30:18.481 › [DeviceService] stopped poll UHK Device
> 14:30:18.482 › [UhkHidDevice] USB[W]: 00 02 
> 14:30:18.487 › [UhkHidDevice] USB[R]: 00 40 00 c0 7f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:18.488 › [UhkHidDevice] Device communication closing.
> 14:30:18.490 › [UhkHidDevice] Device communication closed.
> 14:30:18.495 › [DeviceService] start poll UHK Device
> 14:30:18.496 › [DeviceService] stop poll UHK Device
> 14:30:18.497 › [DeviceService] stopped poll UHK Device
> 14:30:18.506 › [UhkHidDevice] Available devices unchanged
> 14:30:18.563 › [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"/dev/hidraw0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
> 14:30:18.564 › [UhkHidDevice] USB[W]: 09 
> 14:30:19.569 › [UhkHidDevice] USB[R]: 
> 14:30:19.571 › [UhkHidDevice] Device communication closing.
> 14:30:19.573 › [UhkHidDevice] Device communication closed.
> 14:30:19.574 › [DeviceService] start poll UHK Device
> 14:30:19.680 › [UhkHidDevice] Available devices unchanged
> 14:30:19.739 › [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"/dev/hidraw0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
> 14:30:19.741 › [UhkHidDevice] USB[W]: 09 
> 14:30:19.750 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:20.023 › [UhkHidDevice] USB[W]: 09 
> 14:30:20.036 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:20.309 › [UhkHidDevice] USB[W]: 09 
> 14:30:20.317 › Update for version 1.4.3 is not available (latest version: 1.4.3, downgrade is disallowed).
> 14:30:20.319 › [AppUpdateService] checkForUpdate success
> 14:30:20.320 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:20.603 › [UhkHidDevice] USB[W]: 09 
> 14:30:20.612 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:20.893 › [UhkHidDevice] USB[W]: 09 
> 14:30:20.900 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:21.181 › [UhkHidDevice] USB[W]: 09 
> 14:30:21.188 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:21.470 › [UhkHidDevice] USB[W]: 09 
> 14:30:21.480 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:21.756 › [UhkHidDevice] USB[W]: 09 
> 14:30:21.764 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:22.039 › [UhkHidDevice] USB[W]: 09 
> 14:30:22.048 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:22.319 › [UhkHidDevice] USB[W]: 09 
> 14:30:22.324 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:22.600 › [UhkHidDevice] USB[W]: 09 
> 14:30:22.608 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:22.884 › [UhkHidDevice] USB[W]: 09 
> 14:30:22.892 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:23.168 › [UhkHidDevice] USB[W]: 09 
> 14:30:23.176 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:23.443 › [UhkHidDevice] USB[W]: 09 
> 14:30:23.453 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:23.721 › [UhkHidDevice] USB[W]: 09 
> 14:30:23.729 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:24.001 › [UhkHidDevice] USB[W]: 09 
> 14:30:24.009 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:24.284 › [UhkHidDevice] USB[W]: 09 
> 14:30:24.293 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:24.569 › [UhkHidDevice] USB[W]: 09 
> 14:30:24.577 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:24.856 › [UhkHidDevice] USB[W]: 09 
> 14:30:24.865 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:25.147 › [UhkHidDevice] USB[W]: 09 
> 14:30:25.157 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:25.438 › [UhkHidDevice] USB[W]: 09 
> 14:30:25.450 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:25.732 › [UhkHidDevice] USB[W]: 09 
> 14:30:25.741 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:26.015 › [UhkHidDevice] USB[W]: 09 
> 14:30:26.021 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:26.300 › [UhkHidDevice] USB[W]: 09 
> 14:30:26.309 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:26.585 › [UhkHidDevice] USB[W]: 09 
> 14:30:26.593 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:26.869 › [UhkHidDevice] USB[W]: 09 
> 14:30:26.877 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:27.156 › [UhkHidDevice] USB[W]: 09 
> 14:30:27.166 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:27.444 › [UhkHidDevice] USB[W]: 09 
> 14:30:27.454 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:27.729 › [UhkHidDevice] USB[W]: 09 
> 14:30:27.738 › [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
> 14:30:27.741 › [WindowState] save settings: {
>   x: 1618,
>   y: 594,
>   width: 1463,
>   height: 846,
>   isMaximized: false,
>   isFullScreen: false
> }
> 14:30:27.748 › [WindowState] save settings success
> 14:30:27.774 › [Electron Main] win closed
> 14:30:27.776 › [DeviceService] stop poll UHK Device
> 14:30:27.777 › [DeviceService] stopped poll UHK Device
> 14:30:27.778 › [DeviceService] Device connection checker stopped.
> 14:30:27.779 › [UhkHidDevice] Device communication closing.
> 14:30:27.781 › [UhkHidDevice] Device communication closed.
```

**Comment by rightaditya** [comment]
I can try again with different Agent versions if you like (repeating multiple times, etc.).

**Comment by mondalaci** [comment]
@rightaditya Thanks for your further reports! Unfortunately, I'm not sure we can do anything about this. Your dock doesn't seem to support complex USB devices like the UHK properly. A firmware update of your dock might help. We'll try to look to the bottom of such issues eventually, try to make Agent detect such situations and display relevant error messages, but I don't have too much hope regarding fixing this.

**Comment by rightaditya** [comment]
@mondalaci Ehhh it's not a big deal, and I'm glad to have been able to help to whatever extent possible. It was bad when I thought I had to boot into Windows (which I only have on a USB flash drive, slow as hell), but all I need to do is unplug the monitor's USB cable from the dock and into the laptop instead.

FWIW, I wouldn't feel discriminated against if you kept a blacklist... a timeout could be followed by a check to see if the dock is on a known list of problematic devices, and the user informed that that's likely the problem. It may not be worth it, though, for such a rare issue. But I'm happy to provide whatever identifying information might be useful if needed.

**Comment by mondalaci** [comment]
@rightaditya Excellent idea regarding detecting known problematic devices! But instead of blacklisting them, I'd rather shape the error message accordingly. We'll see if we actually need to use such measures.

**Comment by ddelnano** [comment]
I'm experiencing this issue even though I don't have any USB hubs or docks in use. The only other USB devices connected to my computer are an external hard drive and my mouse. Even with disconnecting those devices my UHK keyboard isn't recognized.

I see a continuous stream of the following errors when running agent.

```
21:50:51.637 › [Electron Main] init services.
21:50:51.646 › [Electron Main] packagesDir: /tmp/.mount_UHK.AgSJoVKD/resources

(uhk-agent-ui:143350): Gtk-WARNING **: 21:50:51.670: Failed to parse /home/ddelnano/.config/gtk-3.0/settings.ini: Key file does not have group ?Settings?
21:50:51.809 › [Electron Main] Create new window.
21:50:51.809 › [WindowState] load settings
21:50:51.812 › [WindowState] loaded settings {
  x: 810,
  y: 279,
  width: 1024,
  height: 768,
  isMaximized: false,
  isFullScreen: false
}
21:50:51.817 › [WindowState] loaded settings is visible true
21:50:51.817 › [WindowState] return with loaded settings
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
21:50:52.192 › [DeviceService] start poll UHK Device
21:50:52.232 › [UhkHidDevice] Devices before checking permission:
21:50:52.239 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
21:50:52.240 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw2","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":1}
21:50:52.299 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw3","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":2}
21:50:52.300 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw4","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":3}
21:50:52.301 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw5","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":4}
21:50:52.301 › {"vendorId":2362,"productId":9488,"path":"/dev/hidraw0","serialNumber":"","manufacturer":"PixArt","product":"USB Optical Mouse","release":256,"interface":0}
21:50:52.302 › {"vendorId":1452,"productId":5011,"path":"/dev/hidraw6","serialNumber":"GKXCHLPXLX2Y","manufacturer":"Apple Inc.","product":"AirPod Case","release":512,"interface":0}
21:50:52.360 › [DeviceService] init success
21:50:52.361 › [AppUpdateService] init success
21:50:52.361 › [AppService] init success
21:50:52.362 › [SudoService] App root dir:  /tmp/.mount_UHK.AgSJoVKD/resources
21:50:52.378 › [WindowState] save settings: {
  x: 810,
  y: 308,
  width: 1024,
  height: 768,
  isMaximized: false,
  isFullScreen: false
}
21:50:52.380 › [WindowState] save settings success
21:50:52.383 › [WindowState] save settings: {
  x: 0,
  y: 0,
  width: 1024,
  height: 768,
  isMaximized: false,
  isFullScreen: false
}
21:50:52.385 › [WindowState] save settings success
21:50:52.385 › [WindowState] save settings: {
  x: 810,
  y: 308,
  width: 1024,
  height: 768,
  isMaximized: false,
  isFullScreen: false
}
21:50:52.386 › [WindowState] save settings success
21:50:52.432 › [UhkHidDevice] Available devices:
21:50:52.432 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
21:50:52.433 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw2","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":1}
21:50:52.433 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw3","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":2}
21:50:52.434 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw4","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":3}
21:50:52.434 › {"vendorId":7504,"productId":24866,"path":"/dev/hidraw5","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":4}
21:50:52.435 › {"vendorId":2362,"productId":9488,"path":"/dev/hidraw0","serialNumber":"","manufacturer":"PixArt","product":"USB Optical Mouse","release":256,"interface":0}
21:50:52.436 › {"vendorId":1452,"productId":5011,"path":"/dev/hidraw6","serialNumber":"GKXCHLPXLX2Y","manufacturer":"Apple Inc.","product":"AirPod Case","release":512,"interface":0}
21:50:52.495 › [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0}
21:50:53.502 › [DeviceService] Device connection state query error Error: Communications error with UHK. Response code: undefined
    at t.UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:100:30329)
    at Generator.next (<anonymous>)
    at s (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:43:1759)
21:50:54.767 › [DeviceService] Device connection state query error Error: Communications error with UHK. Response code: undefined
    at t.UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:100:30329)
    at Generator.next (<anonymous>)
    at s (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:43:1759)
21:50:54.899 › [AppRendererService] init success
21:50:54.931 › [DeviceRendererService] init success
21:50:54.936 › Renderer appStart effect start
21:50:54.937 › [AppUpdateService] check for update at startup: { checkForUpdateOnStartUp: true }
21:50:54.939 › [AppUpdateService] app started. Automatically check for update.
21:50:54.941 › firstRunVersion: 1.5.0
21:50:54.941 › package.version: 1.5.4
21:50:54.942 › [AppUpdateService] Application update is skipping at first run.
21:50:54.936 › [AppRendererService] getAppStartInfo
21:50:54.949 › [AppService] getAppStartInfo
21:50:54.937 › Renderer appStart effect end
node:143350) UnhandledPromiseRejectionWarning: Error: Communications error with UHK. Response code: undefined
    at t.UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:100:30329)
    at Generator.next (<anonymous>)
    at s (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:43:1759)
(node:143350) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:143350) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
21:50:56.976 › [DeviceService] Device connection state query error Error: Communications error with UHK. Response code: undefined
    at t.UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:100:30329)
    at Generator.next (<anonymous>)
    at s (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:43:1759)
21:50:58.236 › [DeviceService] Device connection state query error Error: Communications error with UHK. Response code: undefined
    at t.UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:100:30329)
    at Generator.next (<anonymous>)
    at s (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:43:1759)
21:50:59.496 › [DeviceService] Device connection state query error Error: Communications error with UHK. Response code: undefined
    at t.UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:100:30329)
    at Generator.next (<anonymous>)
    at s (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:43:1759)
21:51:00.756 › [DeviceService] Device connection state query error Error: Communications error with UHK. Response code: undefined
    at t.UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:100:30329)
    at Generator.next (<anonymous>)
    at s (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:43:1759)
21:51:02.018 › [DeviceService] Device connection state query error Error: Communications error with UHK. Response code: undefined
    at t.UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:100:30329)
    at Generator.next (<anonymous>)
    at s (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:43:1759)
^C21:51:02.396 › [UhkHidDevice] Transfer error:  Error: could not read data from device
    at t.UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:100:30224)
    at Generator.next (<anonymous>)
    at s (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:43:1759)
21:51:02.398 › [UhkHidDevice] Device communication closing.
21:51:02.400 › [UhkHidDevice] Device communication closed.
21:51:02.400 › [DeviceService] Device connection state query error Error: could not read data from device
    at t.UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:100:30224)
    at Generator.next (<anonymous>)
    at s (/tmp/.mount_UHK.AgSJoVKD/resources/app.asar/electron-main.js:43:1759)
21:51:02.401 › [WindowState] save settings: {
  x: 810,
  y: 308,
  width: 1024,
  height: 768,
  isMaximized: false,
  isFullScreen: false
}
21:51:02.402 › [WindowState] save settings success
21:51:02.407 › [Electron Main] win closed
21:51:02.408 › [DeviceService] stop poll UHK Device
21:51:02.409 › [DeviceService] stopped poll UHK Device
21:51:02.409 › [DeviceService] Device connection checker stopped.
21:51:02.410 › [UhkHidDevice] Device communication closing.

```

Any ideas of what could be going on here?

**Comment by ert78gb** [comment]
what is the OS that you use? Please provide the version number too. Based on the logs you are using Linux.

**Comment by ert78gb** [comment]
Sry I missed the 
> Arch desktop

**Comment by ddelnano** [comment]
It turns out that using the USB 2.0 ports on my motherboard work but the USB 3.0 ports don't. I'll update this comment with my OS version and agent version later.

**Comment by bzed** [comment]
Actually I'm running into the same issue - I have two laptops with debian/unstable, on my T450 I'm running into
```
[   52.391626] usb 2-2: reset full-speed USB device number 19 using xhci_hcd
[   52.519335] usb 2-2: Device not responding to setup address.
[   52.727437] usb 2-2: Device not responding to setup address.
[   52.935171] usb 2-2: device not accepting address 19, error -71
[   53.063255] usb 2-2: reset full-speed USB device number 19 using xhci_hcd
[   53.195489] usb 2-2: Device not responding to setup address.
[   54.783593] usb 2-2: reset full-speed USB device number 19 using xhci_hcd
[   54.932441] usb 2-2: can't restore configuration #1 (error=-71)
[   54.932480] usb 2-2: USB disconnect, device number 19
[   55.391246] usb 2-2: new full-speed USB device number 20 using xhci_hcd
[   55.540602] usb 2-2: unable to read config index 0 descriptor/start: -71
[   55.540610] usb 2-2: can't read configurations, error -71
[   55.667258] usb 2-2: new full-speed USB device number 21 using xhci_hcd
[   55.795334] usb 2-2: Device not responding to setup address.
[   56.003378] usb 2-2: Device not responding to setup address.
[   56.211267] usb 2-2: device not accepting address 21, error -71
[   56.211338] usb usb2-port2: attempt power cycle
[   56.627295] usb 2-2: new full-speed USB device number 22 using xhci_hcd
[   56.649581] usb 2-2: New USB device found, idVendor=1d50, idProduct=6124, bcdDevice= 1.02
[   56.649603] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[   56.649611] usb 2-2: Product: UHK 60 v2
[   56.649618] usb 2-2: Manufacturer: Ultimate Gadget Laboratories
[   56.657718] hid-generic 0003:1D50:6124.002D: hiddev0,hidraw0: USB HID v1.10 Device [Ultimate Gadget Laboratories UHK 60 v2] on usb-0000:00:14.0-2/input0
[   56.663341] input: Ultimate Gadget Laboratories UHK 60 v2 as /devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.1/0003:1D50:6124.002E/input/input56
[   56.724320] hid-generic 0003:1D50:6124.002E: input,hidraw1: USB HID v1.10 Keyboard [Ultimate Gadget Laboratories UHK 60 v2] on usb-0000:00:14.0-2/input1
[   56.725951] input: Ultimate Gadget Laboratories UHK 60 v2 as /devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.2/0003:1D50:6124.002F/input/input57
[   56.783529] hid-generic 0003:1D50:6124.002F: input,hidraw2: USB HID v1.10 Device [Ultimate Gadget Laboratories UHK 60 v2] on usb-0000:00:14.0-2/input2
[   56.784295] input: Ultimate Gadget Laboratories UHK 60 v2 as /devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.3/0003:1D50:6124.0030/input/input58
[   56.843754] hid-generic 0003:1D50:6124.0030: input,hidraw3: USB HID v1.10 Device [Ultimate Gadget Laboratories UHK 60 v2] on usb-0000:00:14.0-2/input3
[   56.844517] input: Ultimate Gadget Laboratories UHK 60 v2 as /devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.4/0003:1D50:6124.0031/input/input59
[   56.844753] hid-generic 0003:1D50:6124.0031: input,hidraw4: USB HID v1.10 Mouse [Ultimate Gadget Laboratories UHK 60 v2] on usb-0000:00:14.0-2/input4
[   57.987907] usb 2-2: reset full-speed USB device number 22 using xhci_hcd
[   58.136266] usb 2-2: device firmware changed
[   58.136355] usb 2-2: USB disconnect, device number 22
[   58.543312] usb 2-2: new full-speed USB device number 23 using xhci_hcd
[   58.692817] usb 2-2: string descriptor 0 read error: -75
[   58.692823] usb 2-2: New USB device found, idVendor=1d50, idProduct=6124, bcdDevice= 1.02
[   58.692826] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[   58.695368] usb 2-2: can't set config #1, error -71
```

while it just works fine on the Lenovo x390. 
My first idea was that it is a power issue, but even after a powered usb hub the same issue shows up.

**Comment by mondalaci** [comment]
@bzed Please check out [this guide](https://ultimatehackingkeyboard.com/repair/fixing-misbehaving-keys), and any further issues, send us an email to support at ultimatehackingkeyboard dot com.

**Comment by bzed** [comment]
@mondalaci the guide is missing the option "the shipped stock usb cable is faulty, try a different one". :) Seems there is a cable broken inside, moving is makes things worse/better. Replaced, everything working fine.

**Comment by mondalaci** [comment]
@bzed Thanks for the heads-up! I better extended the guide ;) Sorry for the issue, and happy you found the solution!

**Comment by bzed** [comment]
@mondalaci no problem. Actually posted into this bug as the agent behaviour was pretty similar on the machine where the keyboard worked.
