### ISSUE TITLE
Firmware update failed

### ISSUE THREAD

**Issue by pwntester** [UltimateHackingKeyboard/agent#793]
Hi,

Im unable to upgrade the firmware, Im getting the following errors:
Im using macOS High Sierra (10.13.6) and already tried doing the upgrade after a fresh reboot with only the UHK plugged in.

UHK is currently using 8.2.5 and I tried to update to 8.4.5, 8.4.0 and 8.3.0 (My goal is being able to define my own macros)

Thanks,
A

```
Start flashing firmware
[14:21:19.959] [UhkHidDevice] Available devices unchanged
[14:21:19.960] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/PRT1@14100000/Ultimate Hacking Keyboard@14100000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14100000,0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":-1,"usagePage":65280,"usage":1}
[14:21:19.960] [UhkHidDevice] USB[W]: 09 
[14:21:19.968] [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[14:21:19.969] [DeviceOperation] USB[T]: Read left module version information
[14:21:19.969] [UhkHidDevice] USB[W]: 0e 01 00 
[14:21:19.977] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 02 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[14:21:19.978] [DeviceOperation] USB[T]: Read right module version information
[14:21:19.978] [UhkHidDevice] USB[W]: 00 01 
[14:21:19.985] [UhkHidDevice] USB[R]: 00 08 00 02 00 05 00 04 00 03 00 01 00 04 00 00 00 00 00 04 00 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[14:21:19.985] Device right firmware version: 8.2.5
[14:21:19.986] Device left firmware version: 8.2.5
[14:21:20.116] New firmware version: 8.4.5
[14:21:20.117] [UhkOperations] Operating system: Darwin 17.7.0 x64
[14:21:20.117] [UhkOperations] Start flashing right firmware
[14:21:20.117] [UhkHidDevice] Start reenumeration, mode: Bootloader
[14:21:20.231] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[14:21:20.232] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[14:21:20.620] [UhkHidDevice] reenumeration devices up
[14:21:20.620] [UhkHidDevice] Device communication closing.
[14:21:20.691] [UhkHidDevice] Device communication closed.
[14:21:20.692] [blhost] RUN: /Applications/UHK Agent.app/Contents/Resources/packages/blhost/mac/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[14:21:20.793] [blhost] EXIT_CODE: null
[14:21:20.793] [blhost] FINISHED: null
[14:21:20.794] [blhost] CLOSE_CODE: null
[14:21:21.070] [DeviceService] updateFirmware error { message: 'blhost error code:null',
  stack: 'Error: blhost error code:null\n    at finish (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:53:35)\n    at ChildProcess.childProcess.on.code (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:36:17)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' }
[14:21:21.078] [UhkHidDevice] Available devices:
[14:21:21.079] {"vendorId":76,"productId":617,"path":"IOService:/IOResources/IOBluetoothHCIController/AppleBroadcomBluetoothHostController/IOBluetoothDevice/IOBluetoothL2CAPChannel/AppleHSBluetoothDevice","serialNumber":"ac-bc-32-df-c2-1e","manufacturer":"Apple","product":"Magic Mouse 2","release":100,"interface":-1,"usagePage":1,"usage":2}
[14:21:21.079] {"vendorId":76,"productId":617,"path":"IOService:/IOResources/IOBluetoothHCIController/AppleBroadcomBluetoothHostController/IOBluetoothDevice/IOBluetoothL2CAPChannel/AppleHSBluetoothDevice/Mouse / Boot@1/AppleHSBluetoothHIDDriver","serialNumber":"ac-bc-32-df-c2-1e","manufacturer":"Apple","product":"Magic Mouse 2","release":0,"interface":-1,"usagePage":1,"usage":2}
[14:21:21.079] {"vendorId":0,"productId":0,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SBUS@1F,3/AppleSMBusPCI/BUS0@0/AppleSMBusControllerICH/MKY0/AppleMikeyDriver/AppleMikeyHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Mikey HID Driver","release":0,"interface":-1,"usagePage":12,"usage":1}
[14:21:21.080] {"vendorId":76,"productId":617,"path":"IOService:/IOResources/IOBluetoothHCIController/AppleBroadcomBluetoothHostController/IOBluetoothDevice/IOBluetoothL2CAPChannel/AppleHSBluetoothDevice/Device Management@0/AppleHSBluetoothHIDDriver","serialNumber":"ac-bc-32-df-c2-1e","manufacturer":"Apple","product":"Magic Mouse 2","release":0,"interface":-1,"usagePage":65280,"usage":11}
[14:21:21.080] {"vendorId":76,"productId":617,"path":"IOService:/IOResources/IOBluetoothHCIController/AppleBroadcomBluetoothHostController/IOBluetoothDevice/IOBluetoothL2CAPChannel/AppleHSBluetoothDevice/Accelerometer@2/AppleHSBluetoothHIDDriver","serialNumber":"ac-bc-32-df-c2-1e","manufacturer":"Apple","product":"Magic Mouse 2","release":0,"interface":-1,"usagePage":65280,"usage":3}
[14:21:21.081] {"vendorId":5824,"productId":10203,"path":"IOService:/IOResources/org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_v060800/org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_UserClient_v060800/org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v060800","serialNumber":"pqrs.org:org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v060800","manufacturer":"pqrs.org","product":"Karabiner VirtualHIDKeyboard","release":0,"interface":-1,"usagePage":1,"usage":6}
[14:21:21.081] {"vendorId":1452,"productId":611,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/EHC1@1D/EHC1@1d000000/PRT1@1d100000/IOUSBHostDevice@1d100000/AppleUSB20InternalIntelHub@1d100000/PRT8@1d180000/IOUSBHostDevice@1d180000/AppleUSB20InternalSMSCHub@1d180000/PRT2@1d182000/Apple Internal Keyboard / Trackpad@1d182000/Apple Internal Keyboard@0/AppleUSBTCKeyboard@1d182000,0","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":546,"interface":-1,"usagePage":1,"usage":6}
[14:21:21.081] {"vendorId":1452,"productId":611,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/EHC1@1D/EHC1@1d000000/PRT1@1d100000/IOUSBHostDevice@1d100000/AppleUSB20InternalIntelHub@1d100000/PRT8@1d180000/IOUSBHostDevice@1d180000/AppleUSB20InternalSMSCHub@1d180000/PRT2@1d182000/Apple Internal Keyboard / Trackpad@1d182000/Touchpad@1/AppleUSBMultitouchDriver@1d182000,1","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":546,"interface":-1,"usagePage":65280,"usage":1}
[14:21:21.082] {"vendorId":7504,"productId":24864,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/PRT1@14100000/UHK Bootloader@14100000/MCU HID GENERIC DEVICE@0/IOUSBHostHIDDevice@14100000,0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":-1,"usagePage":65280,"usage":1}
[14:21:21.082] {"vendorId":1452,"productId":611,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/EHC1@1D/EHC1@1d000000/PRT1@1d100000/IOUSBHostDevice@1d100000/AppleUSB20InternalIntelHub@1d100000/PRT8@1d180000/IOUSBHostDevice@1d180000/AppleUSB20InternalSMSCHub@1d180000/PRT2@1d182000/Apple Internal Keyboard / Trackpad@1d182000/Touchpad@2/AppleUSBTCButtons@1d182000,2","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":546,"interface":-1,"usagePage":1,"usage":2}
[14:21:21.083] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected
    at Promise (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:92:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:89:1)
    at Generator.next (<anonymous>)
    at /Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.write (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:88:1)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:140:1)
    at Generator.next (<anonymous>)

[14:21:21.612] [DeviceService] Device connection state changed to: { bootloaderActive: true, connected: false, hasPermission: true }
blhost error code:null
```

**Comment by mondalaci** [comment]
Which Agent version are you using?

**Comment by pwntester** [comment]
1.2.8

**Comment by pwntester** [comment]
Just tried with 1.2.10 and got:

```
Start flashing firmware
[14:44:17.692] [UhkHidDevice] Available devices unchanged
[14:44:17.694] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/PRT1@14100000/Ultimate Hacking Keyboard@14100000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14100000,0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":-1,"usagePage":65280,"usage":1}
[14:44:17.694] [UhkHidDevice] USB[W]: 09 
[14:44:17.699] [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[14:44:17.699] [DeviceOperation] USB[T]: Read left module version information
[14:44:17.700] [UhkHidDevice] USB[W]: 0e 01 00 
[14:44:17.707] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 02 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[14:44:17.708] [DeviceOperation] USB[T]: Read right module version information
[14:44:17.770] [UhkHidDevice] USB[W]: 00 01 
[14:44:17.775] [UhkHidDevice] USB[R]: 00 08 00 02 00 05 00 04 00 03 00 01 00 04 00 00 00 00 00 04 00 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[14:44:17.776] Device right firmware version: 8.2.5
[14:44:17.776] Device left firmware version: 8.2.5
[14:44:17.938] New firmware version: 8.4.5
[14:44:17.939] [UhkOperations] Operating system: Darwin 17.7.0 x64
[14:44:17.939] [UhkOperations] Start flashing right firmware
[14:44:17.939] [UhkHidDevice] Start reenumeration, mode: Bootloader
[14:44:18.052] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[14:44:18.052] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[14:44:18.445] [UhkHidDevice] reenumeration devices up
[14:44:18.445] [UhkHidDevice] Device communication closing.
[14:44:18.445] [UhkHidDevice] Device communication closed.
[14:44:18.446] [blhost] RUN: /Applications/UHK Agent.app/Contents/Resources/packages/blhost/mac/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[14:44:18.481] [blhost] EXIT_CODE: null
[14:44:18.482] [blhost] FINISHED: null
[14:44:18.482] [blhost] CLOSE_CODE: null
[14:44:18.780] [DeviceService] updateFirmware error { message: 'blhost error code:null',
  stack: 'Error: blhost error code:null\n    at finish (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:53:35)\n    at ChildProcess.childProcess.on.code (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:36:17)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' }
[14:44:18.789] [UhkHidDevice] Available devices:
[14:44:18.789] {"vendorId":7504,"productId":24864,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/PRT1@14100000/UHK Bootloader@14100000/MCU HID GENERIC DEVICE@0/IOUSBHostHIDDevice@14100000,0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":-1,"usagePage":65280,"usage":1}
[14:44:18.790] {"vendorId":76,"productId":617,"path":"IOService:/IOResources/IOBluetoothHCIController/AppleBroadcomBluetoothHostController/IOBluetoothDevice/IOBluetoothL2CAPChannel/AppleHSBluetoothDevice","serialNumber":"ac-bc-32-df-c2-1e","manufacturer":"Apple","product":"Magic Mouse 2","release":100,"interface":-1,"usagePage":1,"usage":2}
[14:44:18.790] {"vendorId":1452,"productId":611,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/EHC1@1D/EHC1@1d000000/PRT1@1d100000/IOUSBHostDevice@1d100000/AppleUSB20InternalIntelHub@1d100000/PRT8@1d180000/IOUSBHostDevice@1d180000/AppleUSB20InternalSMSCHub@1d180000/PRT2@1d182000/Apple Internal Keyboard / Trackpad@1d182000/Touchpad@1/AppleUSBMultitouchDriver@1d182000,1","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":546,"interface":-1,"usagePage":65280,"usage":1}
[14:44:18.790] {"vendorId":1452,"productId":611,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/EHC1@1D/EHC1@1d000000/PRT1@1d100000/IOUSBHostDevice@1d100000/AppleUSB20InternalIntelHub@1d100000/PRT8@1d180000/IOUSBHostDevice@1d180000/AppleUSB20InternalSMSCHub@1d180000/PRT2@1d182000/Apple Internal Keyboard / Trackpad@1d182000/Touchpad@2/AppleUSBTCButtons@1d182000,2","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":546,"interface":-1,"usagePage":1,"usage":2}
[14:44:18.791] {"vendorId":1452,"productId":611,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/EHC1@1D/EHC1@1d000000/PRT1@1d100000/IOUSBHostDevice@1d100000/AppleUSB20InternalIntelHub@1d100000/PRT8@1d180000/IOUSBHostDevice@1d180000/AppleUSB20InternalSMSCHub@1d180000/PRT2@1d182000/Apple Internal Keyboard / Trackpad@1d182000/Apple Internal Keyboard@0/AppleUSBTCKeyboard@1d182000,0","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":546,"interface":-1,"usagePage":1,"usage":6}
[14:44:18.791] {"vendorId":76,"productId":617,"path":"IOService:/IOResources/IOBluetoothHCIController/AppleBroadcomBluetoothHostController/IOBluetoothDevice/IOBluetoothL2CAPChannel/AppleHSBluetoothDevice/Mouse / Boot@1/AppleHSBluetoothHIDDriver","serialNumber":"ac-bc-32-df-c2-1e","manufacturer":"Apple","product":"Magic Mouse 2","release":0,"interface":-1,"usagePage":1,"usage":2}
[14:44:18.791] {"vendorId":0,"productId":0,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SBUS@1F,3/AppleSMBusPCI/BUS0@0/AppleSMBusControllerICH/MKY0/AppleMikeyDriver/AppleMikeyHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Mikey HID Driver","release":0,"interface":-1,"usagePage":12,"usage":1}
[14:44:18.791] {"vendorId":76,"productId":617,"path":"IOService:/IOResources/IOBluetoothHCIController/AppleBroadcomBluetoothHostController/IOBluetoothDevice/IOBluetoothL2CAPChannel/AppleHSBluetoothDevice/Accelerometer@2/AppleHSBluetoothHIDDriver","serialNumber":"ac-bc-32-df-c2-1e","manufacturer":"Apple","product":"Magic Mouse 2","release":0,"interface":-1,"usagePage":65280,"usage":3}
[14:44:18.791] {"vendorId":5824,"productId":10203,"path":"IOService:/IOResources/org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_v060800/org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_UserClient_v060800/org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v060800","serialNumber":"pqrs.org:org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v060800","manufacturer":"pqrs.org","product":"Karabiner VirtualHIDKeyboard","release":0,"interface":-1,"usagePage":1,"usage":6}
[14:44:18.792] {"vendorId":76,"productId":617,"path":"IOService:/IOResources/IOBluetoothHCIController/AppleBroadcomBluetoothHostController/IOBluetoothDevice/IOBluetoothL2CAPChannel/AppleHSBluetoothDevice/Device Management@0/AppleHSBluetoothHIDDriver","serialNumber":"ac-bc-32-df-c2-1e","manufacturer":"Apple","product":"Magic Mouse 2","release":0,"interface":-1,"usagePage":65280,"usage":11}
[14:44:18.793] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected
    at Promise (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:92:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:89:1)
    at Generator.next (<anonymous>)
    at /Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.write (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:88:1)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:140:1)
    at Generator.next (<anonymous>)

[14:44:19.326] [DeviceService] Device connection state changed to: { bootloaderActive: true, connected: false, hasPermission: true }
blhost error code:null
```

**Comment by mondalaci** [comment]
Looks like #747 is still not completely resolved on some Macs. We won't mess with blhost anymore because it's a short-term, incomplete solution. Rather, we'll fix #755 which is the long-term solution.

In the meantime, please use another computer to upgrade your UHK firmware. I'm sorry I can't offer a better solution at the moment. I'm closing this issue in favor of #755.

**Comment by pwntester** [comment]
I only have Macs and it fails on all of them, so please prioritize #755 fix, thanks!

**Comment by mondalaci** [comment]
Will do.

**Comment by kareltucek** [comment]
If it is still the same problem, recompiling the binary with proper flags shouldn't be that hard...

**Comment by kareltucek** [comment]
The C language is not magic. Any mainstream C compiler should do as long as:
- the thing compiles
- the thing specifies a flag which explicitly forbids native optimisations. Any compiler necessarily does have this, because all software intended for wide distribution has to be compiled in such mode.

I have never owned a Mac machine, so I may be of very limited help here. Still: 
- I don't remember anyone discussing any attempt to get the flags right on mac. Did anyone at least try? (I mean, @ert78gb never responded to your request for his xcode file in https://github.com/UltimateHackingKeyboard/agent/issues/747 , so I assume that he only recompiled on his machine, which might have falsely seemed to solve something.)
- I assume that crashing due to invalid instructions and hanging usb ports are two completely unrelated issues? 
- Just compiling on different C compiler or version or computer doesn't solve anything even though it may seem like that. Getting flags (the march flag) right is the important part. 
- I assume we are talking about one specific architecture on which mac runs, right? I assume it is 64bit x86.
- If I am correct, you use Xcode on mac, which is just an IDE built on top of GCC right?
- If I am correct, you have one makefile for linux and then a separate xcode projec for mac, right? I assume that it means that you use some automatically generated compiling machinery stored within the xcode project which is completely unrelated to the linux makefile? 
- In that case, applying the same march flags (in case the architecture is 64bit x86) or the corresponding flags (if the architecture is different) in Xcode should work. No?

**Comment by mondalaci** [comment]
Sorry, but I won't spend any more time on trying to get blhost built correctly, because I consider it to be counterproductive based on my experience. #755 is the way to go.

**Comment by ert78gb** [comment]
@kareltucek I committed my xcode configs on 21th Aug. https://github.com/UltimateHackingKeyboard/bootloader/tree/chore-change-xcode-project-settings branch
u could check it, compile own version. test it and if it working on ur machine PR more than welcome
thx

**Comment by kareltucek** [comment]
> I committed my xcode configs on 21th Aug

Oh, didn't notice, sorry! 

I don't see actual changes since the diff just replaces everything...

> u could check it, compile own version

As I said, I never owned and still don't own any Mac machine. I can't even set up Xcode to see available options since it is said to run on Mac only natively. Setting up an environment *and* testing this properly would require setting up two different virtual machines on my side, including simulation of different architecture (using Qemu?).

I don't understand the format in https://github.com/UltimateHackingKeyboard/bootloader/commit/0ca41901b56bfcd4f5e23696c2f4eeaf6aab21e5 , but if the 02B3B3BC16DE7116009769BD section applies, then ONLY_ACTIVE_ARCH is set to YES in all release versions/types, which I think translates into setting "march=native" in gcc/clang (which is not good). I believe the necessary setting is ONLY_ACTIVE_ARCH=NO and ARCHS to the list of archs which you want to support on different machines. I assume that the list can easily be the same as the default listed in VALID_ARCHS (and that it should make sense).  

See ONLY_ACTIVE_ARCH, VALID_ARCHS, ARCHS at https://developer.apple.com/library/archive/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html#//apple_ref/doc/uid/TP40003931-CH3-SW62

...If I wanted to debug this more, I would try to find out what Xcode actually passes to the underlying compiler...

Anyway, I am available if you have any questions, but I am not going to dig into this myself much deeper (or pester you guys anymore). (I have no personal interest in this and not being a mac guy makes any digging difficult for me - sorry!)

**Comment by mondalaci** [comment]
@pwntester Please close Karabiner Elements and retry the firmware update.

**Comment by pwntester** [comment]
It worked, thanks!
Actually, I dont need Karabiner anymore now that I have UHK :)
