### ISSUE TITLE
Can't update a firmware on Ubuntu16.04

### ISSUE THREAD

**Issue by hypnobear33** [UltimateHackingKeyboard/agent#875]
I have the latest agent and can't update a firmware. Here is a log:
```
Start flashing firmware
[15:30:59.033] Agent version: 1.2.12
[15:30:59.037] [UhkHidDevice] Available devices unchanged
[15:30:59.096] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":0,"usagePage":26995,"usage":28271}
[15:30:59.096] [UhkHidDevice] USB[W]: 09 
[15:30:59.102] [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[15:30:59.103] [DeviceOperation] USB[T]: Read left module version information
[15:30:59.104] [UhkHidDevice] USB[W]: 0e 01 00 
[15:30:59.110] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 02 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[15:30:59.111] [DeviceOperation] USB[T]: Read right module version information
[15:30:59.112] [UhkHidDevice] USB[W]: 00 01 
[15:30:59.118] [UhkHidDevice] USB[R]: 00 08 00 02 00 05 00 04 00 03 00 01 00 04 00 00 00 00 00 04 00 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[15:30:59.120] Device right firmware version: 8.2.5
[15:30:59.120] Device left firmware version: 8.2.5
[15:30:59.122] New firmware version: 8.5.3
[15:30:59.123] [UhkOperations] Operating system: Linux 4.15.0-42-generic x64
[15:30:59.123] [UhkOperations] Start flashing right firmware
[15:30:59.124] [UhkHidDevice] Start reenumeration, mode: Bootloader
[15:30:59.230] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[15:30:59.230] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[15:31:00.014] [UhkHidDevice] reenumeration devices up
[15:31:00.014] [UhkHidDevice] Device communication closing.
[15:31:00.014] [UhkHidDevice] Device communication closed.
[15:31:00.015] [blhost] RUN: /tmp/.mount_UHK.AgXwoog6/resources/packages/blhost/linux/x86_64/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[15:31:00.037] [blhost] STDOUT: Error: UsbHidPeripheral() cannot open USB HID device (vid=0x1d50, pid=0x6120, sn=).
[15:31:00.038] [blhost] EXIT_CODE: 1
[15:31:00.039] [blhost] FINISHED: 1
[15:31:00.040] [DeviceService] updateFirmware error { message: 'blhost error code:1',
  stack: 'Error: blhost error code:1\n    at finish (/tmp/.mount_UHK.AgXwoog6/resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:53:35)\n    at ChildProcess.childProcess.on.code (/tmp/.mount_UHK.AgXwoog6/resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:36:17)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' }
[15:31:00.043] [UhkHidDevice] Available devices:
[15:31:00.043] {"vendorId":7504,"productId":24864,"path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":0,"usagePage":95}
[15:31:00.044] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected
    at Promise (/tmp/.mount_UHK.AgXwoog6/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:107:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgXwoog6/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:104:1)
    at Generator.next (<anonymous>)
    at /tmp/.mount_UHK.AgXwoog6/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/tmp/.mount_UHK.AgXwoog6/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.write (/tmp/.mount_UHK.AgXwoog6/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:103:1)
    at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgXwoog6/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:155:1)
    at Generator.next (<anonymous>)

[15:31:00.046] [blhost] CLOSE_CODE: 1
blhost error code:1
```

**Comment by hypnobear33** [comment]
Here is dmesg:
```
[83559.874116] hid-generic 0003:1D50:6120.0018: hiddev0,hidraw1: USB HID v1.00 Device [Ultimate Gadget Laboratories UHK Bootloader] on usb-0000:00:14.0-3/input0
[83564.178449] usb 1-3: USB disconnect, device number 11
[83564.486177] usb 1-3: new full-speed USB device number 12 using xhci_hcd
[83564.639290] usb 1-3: New USB device found, idVendor=1d50, idProduct=6122
[83564.639291] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[83564.639292] usb 1-3: Product: Ultimate Hacking Keyboard
[83564.639293] usb 1-3: Manufacturer: Ultimate Gadget Laboratories
[83564.640307] hid-generic 0003:1D50:6122.0019: hiddev0,hidraw1: USB HID v1.10 Device [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-3/input0
[83564.640761] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.1/0003:1D50:6122.001A/input/input50
[83564.698437] hid-generic 0003:1D50:6122.001A: input,hidraw2: USB HID v1.10 Keyboard [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-3/input1
[83564.698849] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.2/0003:1D50:6122.001B/input/input51
[83564.758314] hid-generic 0003:1D50:6122.001B: input,hidraw3: USB HID v1.10 Device [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-3/input2
[83564.758829] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.3/0003:1D50:6122.001C/input/input52
[83564.818293] hid-generic 0003:1D50:6122.001C: input,hidraw4: USB HID v1.10 Device [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-3/input3
[83564.818797] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.4/0003:1D50:6122.001D/input/input53
[83564.818900] hid-generic 0003:1D50:6122.001D: input,hidraw5: USB HID v1.10 Mouse [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-3/input4
[84131.604993] usb 1-3: USB disconnect, device number 12
[84132.220313] usb 1-3: new full-speed USB device number 13 using xhci_hcd
[84132.369832] usb 1-3: New USB device found, idVendor=1d50, idProduct=6120
[84132.369837] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[84132.369841] usb 1-3: Product: UHK Bootloader
[84132.369845] usb 1-3: Manufacturer: Ultimate Gadget Laboratories
[84132.372206] hid-generic 0003:1D50:6120.001E: hiddev0,hidraw1: USB HID v1.00 Device [Ultimate Gadget Laboratories UHK Bootloader] on usb-0000:00:14.0-3/input0
[84136.606841] usb 1-3: USB disconnect, device number 13
[84136.912282] usb 1-3: new full-speed USB device number 14 using xhci_hcd
[84137.061361] usb 1-3: New USB device found, idVendor=1d50, idProduct=6122
[84137.061362] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[84137.061364] usb 1-3: Product: Ultimate Hacking Keyboard
[84137.061364] usb 1-3: Manufacturer: Ultimate Gadget Laboratories
[84137.062377] hid-generic 0003:1D50:6122.001F: hiddev0,hidraw1: USB HID v1.10 Device [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-3/input0
[84137.062800] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.1/0003:1D50:6122.0020/input/input54
[84137.120546] hid-generic 0003:1D50:6122.0020: input,hidraw2: USB HID v1.10 Keyboard [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-3/input1
[84137.121041] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.2/0003:1D50:6122.0021/input/input55
[84137.180421] hid-generic 0003:1D50:6122.0021: input,hidraw3: USB HID v1.10 Device [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-3/input2
[84137.180938] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.3/0003:1D50:6122.0022/input/input56
[84137.240425] hid-generic 0003:1D50:6122.0022: input,hidraw4: USB HID v1.10 Device [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-3/input3
[84137.240925] input: Ultimate Gadget Laboratories Ultimate Hacking Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.4/0003:1D50:6122.0023/input/input57
[84137.241051] hid-generic 0003:1D50:6122.0023: input,hidraw5: USB HID v1.10 Mouse [Ultimate Gadget Laboratories Ultimate Hacking Keyboard] on usb-0000:00:14.0-3/input4
```

**Comment by hypnobear33** [comment]
Yes, I've set udev rules)

**Comment by mondalaci** [comment]
Please `cat /etc/udev/rules.d/50-uhk60.rules`

**Comment by hypnobear33** [comment]
```
# Ultimate Hacking Keyboard rules
# These are the udev rules for accessing the USB interfaces of the UHK as non-root users.
# Copy this file to /etc/udev/rules.d and physically reconnect the UHK afterwards.
SUBSYSTEM=="input", GROUP="input", MODE="0666"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", MODE:="0666", GROUP="plugdev"
KERNEL=="hidraw*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", MODE="0666", GROUP="plugdev"
```

**Comment by mondalaci** [comment]
Maybe you don't belong to the plugdev group. Please check.

Which distro are you using?

**Comment by hypnobear33** [comment]
```sh
$ id
uid=1000(hypnobear) gid=1000(hypnobear) groups=1000(hypnobear),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),113(lpadmin),129(sambashare),999(docker)
```
I'm on Ubuntu 16.04

**Comment by mondalaci** [comment]
Quite frankly, I don't know what's the cause of this issue. It works for everyone else, so this may be an installation-specific issue.

It's weird that Agent is able to access the UHK device, but unable to access the bootloader device because both are covered by the udev file. Any ideas, @ert78gb?

Until we figure this out, please update the firmware of your UHK on another computer. #755 might fix this one, but it should already work.

**Comment by ert78gb** [comment]
@mondalaci 
Very interest. The blhost result code 1.
`
[15:31:00.015] [blhost] RUN: /tmp/.mount_UHK.AgXwoog6/resources/packages/blhost/linux/x86_64/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[15:31:00.037] [blhost] STDOUT: Error: UsbHidPeripheral() cannot open USB HID device (vid=0x1d50, pid=0x6120, sn=).
[15:31:00.038] [blhost] EXIT_CODE: 1
[15:31:00.039] [blhost] FINISHED: 1
`

We experience this issue only when UHK device connected via USB hub

**Comment by hypnobear33** [comment]
I connected UHK directly to the USB port of my laptop, no hubs.
Managed to flash a new firmware using macbook.

**Comment by ert78gb** [comment]
Have you tried updating the firmware on the Ubuntu after you updated on Mac? The Agent currently does not check the new and current version of the firmware are match it just start the firmware upgrade.
If you have time could you check it? thx

**Comment by hypnobear33** [comment]
Yes, sure. I've tried just now and had the same error. 
BTW on Ubuntu, I'm using AppImage build. On the mac, I'm using brew installation

**Comment by mondalaci** [comment]
@hypnobear33 This must be a permission issue on your side. There's no other explanation I can think of. What happens if you run Agent as root?

**Comment by hypnobear33** [comment]
It works if I run Agent as root, but I'd like to omit running apps in the root mode. 
My issue is resolved, so I'll close this one. Please fix a permissions issue in AppImage build.

BTW, thank you for the great keyboard!

**Comment by mondalaci** [comment]
I wish we could fix this one, but I still don't know the root cause. So far, this issue only happened on your system. In any case, I'm pretty sure that #755 should resolve this.

Thank you for your support!

**Comment by duesenklipper** [comment]
I have encountered the same thing just now, running on Ubuntu 18.04.1. Running Agent as root let me flash the firmware correctly, so that is a workaround for now.
